var propertyContent = {
  "en": {
    "hero_subtitle": "Strategic Investment Opportunity on 6-Rai in Hua Hin's Rapid Growth Zone",
    "featured_title": "Prime Development Land",
    "featured_subtitle": "A rare 6-Rai parcel with full Chanote title, perfectly positioned for luxury resorts, residential estates, or industrial facilities.",
    "about_title": "Strategic Investment Asset",
    "about_desc": "This expansive 6-Rai (9,600 sqm) parcel of land represents a premier development opportunity in the rapidly evolving Hua Hin corridor. Set against a serene backdrop of pineapple farms and private estates, with neighboring pool villa projects nearby, the site is optimized for diverse high-value projects. Characterized by flat topography and immediate concrete road accessibility, the site provides the foundation for significant capital appreciation. From boutique wellness retreats to modern logistics hubs or specialized retirement villages, this asset is build-ready. Acquire directly from the owner for a streamlined acquisition.",
    "stat_room_title": "Total Area",
    "stat_room_desc": "6 Rai (9,600 sq.m.)",
    "stat_scale_title": "Legal Status",
    "stat_scale_desc": "Chanote (Red Garuda N.S. 4 J.)",
    "stat_loc_title": "Zoning",
    "stat_loc_desc": "Supports diverse development",
    "stat_width_title": "Road Frontage",
    "stat_width_desc": "Bordering public access",
    "price_amount": "฿20,000,000 THB",
    "value_main_title": "Investor Highlights",
    "value_main_subtitle": "Maximize your ROI with a property that is ready for immediate use and long-term value appreciation.",
    "value_live_1_str": "Superior Connectivity:",
    "value_live_1_desc": "Strategically located with links to major transit routes, ensuring logistical efficiency.",
    "value_live_2_str": "Secure Ownership:",
    "value_live_2_desc": "Clear Red Garuda Title Deed ensures legal certainty and easy financing transitions.",
    "value_live_3_str": "Build-Ready Terrain:",
    "value_live_3_desc": "Naturally flat land saves on costly fill or complex grading requirements.",
    "feat_main_title": "Core Infrastructure",
    "feat_main_subtitle": "The site is equipped with essential features that simplify the development process.",
    "feat_pool_title": "Expansive Plot",
    "feat_pool_desc": "A substantial 6-Rai footprint providing limitless design flexibility for large-scale developments.",
    "feat_gym_title": "Infrastructure Access",
    "feat_gym_desc": "Bordered by a quality concrete road, offering seamless logistics for construction and future operations.",
    "feat_walk_title": "High-Value Setting",
    "feat_walk_desc": "Positioned in a tranquil yet developing area, balancing privacy with urban convenience.",
    "feat_peace_title": "Utility Integration",
    "feat_peace_desc": "Electricity and water access points are available nearby, reducing lead times for service connection.",
    "feat_park_title": "Clear Boundaries",
    "feat_park_desc": "Recent survey markers confirm exact borders, ensuring no encroachment issues.",
    "feat_sec_title": "Low Prep Cost",
    "feat_sec_desc": "Immediate project kickoff potential without the need for extensive site clearing or land correction.",
    "loc_condo_name": "Strategic Hua Hin Land",
    "loc_condo_addr": "Hua Hin, Prachuap Khiri Khan 77110",
    "loc_condo_desc": "Positioned in the growth corridor, bridging luxury living with operational functionality.",
    "loc_card1_title": "Hua Hin Beachside",
    "loc_card1_desc": "A primary tourism driver that maintains consistent demand in the area.",
    "loc_card1_dist": "~15 Mins Drive",
    "loc_card2_title": "Commercial Hub",
    "loc_card2_desc": "Close proximity to city amenities, markets, and administrative centers.",
    "loc_card2_dist": "~12 Mins Drive",
    "loc_card3_title": "Recreation & Leisure",
    "loc_card3_desc": "Surrounded by world-class golf courses and family-oriented attractions.",
    "loc_card3_dist": "~5 Mins Drive",
    "loc_card4_title": "Lifestyle Retail",
    "loc_card4_desc": "Easy access to premium shopping malls and international dining.",
    "loc_card4_dist": "~15 Mins Drive",
    "loc_card5_title": "Transport Access",
    "loc_card5_desc": "Near Hua Hin Airport and regional transit corridors.",
    "loc_card5_dist": "~25 Mins Drive",
    "loc_card6_title": "Family Entertainment",
    "loc_card6_desc": "Home to Asia's leading water jungle and outdoor activities.",
    "loc_card6_dist": "~20 Mins Drive",
    "loc_card7_title": "Medical Excellence",
    "loc_card7_desc": "Minutes away from top-tier international healthcare facilities.",
    "loc_card7_dist": "~20 Mins Drive",
    "loc_card8_title": "Major Junction/Retail",
    "loc_card8_desc": "A strategic landmark on the main artery connecting to Bangkok.",
    "loc_card8_dist": "~25 Mins Drive",
    "loc_main_subtitle": "Strategically positioned to leverage Hua Hin's expanding infrastructure and tourism reach.",
    "gal_flt_bld": "Land Assets",
    "gal_flt_liv": "Mapping",
    "gal_flt_fac": "Connectivity",
    "video_section_title": "Aerial Perspective",
    "video_section_subtitle": "Experience the scale and potential of this 6-Rai asset through our drone footage.",
    "potential_title": "High-Yield Development Potential",
    "potential_subtitle": "Engineered for flexibility, this land supports various high-value development models.",
    "pot_resort_title": "Hospitality & Wellness",
    "pot_resort_desc": "Perfect for a boutique resort, a specialized elderly care center, or a peaceful retirement village.",
    "pot_housing_title": "Residential Communities",
    "pot_housing_desc": "Ideal for a secure housing estate, luxury villas, or a private cluster of second homes.",
    "pot_warehouse_title": "Logistics & Storage",
    "pot_warehouse_desc": "Leverage road accessibility for smart storage solutions or distribution centers.",
    "pot_factory_title": "Commercial Industrial",
    "pot_factory_desc": "Tailor-made for light manufacturing or tech-ready industrial facilities.",
    "contact_col_loc_desc": "6-Rai Strategic Land<br>Hua Hin, Prachuap Khiri Khan"
  },
  "th": {
    "hero_subtitle": "โอกาสการลงทุนเชิงกลยุทธบนที่ดิน 6 ไร่ ในโซนที่มีการเติบโตสูงของหัวหิน",
    "featured_title": "ที่ดินเพื่อการพัฒนา ทำเลทอง",
    "featured_subtitle": "เนื้อที่ 6 ไร่ พร้อมโฉนดครุฑแดง เหมาะอย่างยิ่งสำหรับรีสอร์ทหรู โครงการหมู่บ้าน หรืออาคารพาณิชย์และโกดัง",
    "about_title": "สินทรัพย์เพื่อการลงทุนเชิงกลยุทธ์",
    "about_desc": "ที่ดินผืนใหญ่ขนาด 6 ไร่ (9,600 ตร.ม.) นี้เป็นโอกาสทองสำหรับการพัฒนาในระเบียงเศรษฐกิจที่กำลังเติบโตของหัวหิน ท่ามกลางบรรยากาศที่เงียบสงบของสวนสับปะรดและบ้านพักส่วนตัว พร้อมทั้งมีโครงการพูลวิลล่าอยู่ใกล้เคียง ด้วยลักษณะภูมิประเทศที่ราบเรียบและติดถนนคอนกรีตสาธารณะ พื้นที่นี้ได้รับการปรับปรุงให้เหมาะสำหรับโครงการที่มีมูลค่าสูงหลากหลายประเภท เช่น สถานที่พักผ่อนเชิงสุขภาพระดับพรีเมียม ศูนย์การแพทย์และสวัสดิการผู้สูงอายุ หรือคลังสินค้าที่ทันสมัย ซื้อขายโดยตรงจากเจ้าของเพื่อความสะดวกและประหยัดค่านายหน้า",
    "stat_room_title": "เนื้อที่ทั้งหมด",
    "stat_room_desc": "6 ไร่ (9,600 ตร.ม.)",
    "stat_scale_title": "สถานะทางกฎหมาย",
    "stat_scale_desc": "โฉนด (ครุฑแดง น.ส. 4 จ.)",
    "stat_loc_title": "ผังเมือง",
    "stat_loc_desc": "รองรับการพัฒนาที่หลากหลาย",
    "stat_width_title": "หน้ากว้างถนน",
    "stat_width_desc": "ติดทางสาธารณะกว้าง",
    "price_amount": "฿20,000,000 บาท",
    "value_main_title": "จุดเด่นสำหรับนักลงทุน",
    "value_main_subtitle": "เพิ่มผลตอบแทนสูงสุดด้วยอสังหาริมทรัพย์ที่พร้อมใช้งานทันทีและมีมูลค่าเพิ่มขึ้นในระยะยาว",
    "value_live_1_str": "การเชื่อมต่อที่ยอดเยี่ยม:",
    "value_live_1_desc": "ตั้งอยู่ในทำเลเชิงกลยุทธ์ที่เชื่อมต่อกับเส้นทางคมนาคมหลัก มั่นใจได้ในประสิทธิภาพด้านการขนส่ง",
    "value_live_2_str": "กรรมสิทธิ์ที่ปลอดภัย:",
    "value_live_2_desc": "โฉนดที่ดินครุฑแดงที่ชัดเจน มั่นใจได้ในความถูกต้องตามกฎหมายและง่ายต่อการขอสินเชื่อ",
    "value_live_3_str": "พื้นที่พร้อมก่อสร้าง:",
    "value_live_3_desc": "ที่ดินที่ราบเรียบตามธรรมชาติช่วยประหยัดค่าใช้จ่ายในการถมที่หรือการปรับระดับพื้นที่ที่ยุ่งยาก",
    "feat_main_title": "โครงสร้างพื้นฐานหลัก",
    "feat_main_subtitle": "พื้นที่นี้ประกอบด้วยคุณสมบัติสำคัญที่ช่วยให้กระบวนการพัฒนาง่ายขึ้น",
    "feat_pool_title": "ที่ดินผืนใหญ่",
    "feat_pool_desc": "พื้นที่ 6 ไร่ที่กว้างขวาง มอบความยืดหยุ่นไร้ขีดจำกัดในการออกแบบสำหรับโครงการขนาดใหญ่",
    "feat_gym_title": "เข้าถึงสาธารณูปโภค",
    "feat_gym_desc": "ติดถนนคอนกรีตสาธารณะ มอบความสะดวกในการขนส่งสำหรับงานก่อสร้างและการดำเนินงานในอนาคต",
    "feat_walk_title": "สภาพแวดล้อมมูลค่าสูง",
    "feat_walk_desc": "อยู่ในพื้นที่ที่เงียบสงบแต่กำลังพัฒนา ให้ความลงตัวระหว่างความเป็นส่วนตัวและความสะดวกสบาย",
    "feat_peace_title": "ระบบสาธารณูปโภคพร้อม",
    "feat_peace_desc": "ระบบไฟฟ้าและน้ำประปาเข้าถึงพื้นที่ ช่วยลดระยะเวลาในการขอใช้บริการ",
    "feat_park_title": "แนวเขตชัดเจน",
    "feat_park_desc": "ผ่านการรังวัดล่าสุด ยืนยันแนวเขตที่ถูกต้อง มั่นใจไม่มีปัญหาการบุกรุก",
    "feat_sec_title": "ค่าเตรียมพื้นที่ต่ำ",
    "feat_sec_desc": "ที่ดินพร้อมใช้งานทันที ไม่ต้องมีงานปรับสภาพดินที่ยุ่งยาก สามารถเริ่มงานพื้นฐานได้เลย",
    "loc_condo_name": "ที่ดินยุทธศาสตร์ หัวหิน",
    "loc_condo_addr": "หัวหิน, ประจวบคีรีขันธ์ 77110",
    "loc_condo_desc": "ตั้งอยู่ในทำเลศักยภาพของการพัฒนา เชื่อมต่อความหรูหราและการใช้งานได้อย่างลงตัว",
    "loc_card1_title": "ชายหาดหัวหิน",
    "loc_card1_desc": "ปัจจัยหลักขับเคลื่อนการท่องเที่ยวที่สร้างความต้องการอย่างต่อเนื่องในพื้นที่",
    "loc_card1_dist": "ขับรถ ~15 นาที",
    "loc_card2_title": "ศูนย์กลางธุรกิจ",
    "loc_card2_desc": "ตั้งอยู่ใกล้สิ่งอำนวยความสะดวกในเมือง ตลาด และศูนย์ราชการ",
    "loc_card2_dist": "ขับรถ ~12 นาที",
    "loc_card3_title": "สันทนาการและการพักผ่อน",
    "loc_card3_desc": "ล้อมรอบด้วยสนามกอล์ฟระดับโลกและสถานที่ท่องเที่ยวสำหรับครอบครัว",
    "loc_card3_dist": "ขับรถ ~5 นาที",
    "loc_card4_title": "ห้างสรรพสินค้าไลฟ์สไตล์",
    "loc_card4_desc": "เข้าถึงแหล่งช้อปปิ้งระดับพรีเมียมและร้านอาหารนานาชาติได้อย่างง่ายดาย",
    "loc_card4_dist": "ขับรถ ~15 นาที",
    "loc_card5_title": "การเข้าถึงการคมนาคม",
    "loc_card5_desc": "ใกล้สนามบินหัวหินและแนวเส้นทางคมนาคมระดับภูมิภาค",
    "loc_card5_dist": "ขับรถ ~25 นาที",
    "loc_card6_title": "ความบันเทิงสำหรับครอบครัว",
    "loc_card6_desc": "แหล่งรวมสวนน้ำชั้นนำและกิจกรรมกลางแจ้งที่เป็นที่นิยม",
    "loc_card6_dist": "ขับรถ ~20 นาที",
    "loc_card7_title": "การแพทย์ชั้นนำ",
    "loc_card7_desc": "ใกล้สถานพยาบาลระดับนานาชาติชั้นนำในพื้นที่",
    "loc_card7_dist": "ขับรถ ~20 นาที",
    "loc_card8_title": "จุดพักรถและแหล่งช้อปปิ้งหลัก",
    "loc_card8_desc": "จุดแลนด์มาร์คสำคัญบนถนนเส้นหลักที่เชื่อมต่อสู่กรุงเทพฯ",
    "loc_card8_dist": "ขับรถ ~25 นาที",
    "loc_main_subtitle": "วางตำแหน่งอย่างเหมาะสมเพื่อใช้ประโยชน์จากการขยายตัวของโครงสร้างพื้นฐานและการท่องเที่ยวของหัวหิน",
    "gal_flt_bld": "ทรัพย์สินที่ดิน",
    "gal_flt_liv": "การแผนที่",
    "gal_flt_fac": "การเชื่อมต่อ",
    "video_section_title": "ข้อมูลแบบมุมสูง",
    "video_section_subtitle": "สัมผัสศักยภาพและขนาดของที่ดินผืนนี้ผ่านมุมมองโดรນ",
    "potential_title": "ศักยภาพการพัฒนาที่ให้ผลตอบแทนสูง",
    "potential_subtitle": "ออกแบบมาเพื่อความยืดหยุ่น ที่ดินผืนนี้รองรับโมเดลการพัฒนาที่มีมูลค่าสูงหลากหลายประเภท",
    "pot_resort_title": "การบริการและสุขภาพ",
    "pot_resort_desc": "เหมาะสำหรับการพัฒนาบูทีครีสอร์ท ศูนย์ดูแลผู้สูงอายุแบบครบวงจร หรือหมู่บ้านพักตากอากาศที่เงียบสงบ",
    "pot_housing_title": "ชุมชนที่อยู่อาศัย",
    "pot_housing_desc": "เหมาะสำหรับโครงการบ้านจัดสรร วิลล่าหรู หรือกลุ่มบ้านพักตากอากาศส่วนตัว",
    "pot_warehouse_title": "โลจิสติกส์และคลังสินค้า",
    "pot_warehouse_desc": "ใช้ประโยชน์จากการเข้าถึงถนนเพื่อสร้างคลังสินค้าอิฉริยะหรือศูนย์กระจายสินค้า",
    "pot_factory_title": "อุตสาหกรรมและพาณิชย์",
    "pot_factory_desc": "ออกแบบมาเป็นพิเศษสำหรับการผลิตอุตสาหกรรมเบา หรือสิ่งอำนวยความสะดวกด้านเทคโนโลยี",
    "contact_col_loc_desc": "ที่ดินยุทธศาสตร์ 6 ไร่<br>หัวหิน, ประจวบคีรีขันธ์"
  },
  "zh": {
    "hero_subtitle": "华欣快速增长区 6 莱土地的战略投资机会",
    "featured_title": "顶级开发地块",
    "featured_subtitle": "稀有的 6 莱土地，拥有完整 Chanote 产权证，非常适合豪华度假村、住宅区或工业设施。",
    "about_title": "战略投资资产",
    "about_desc": "这块占地 6 莱（9,600 平方米）的土地代表了华欣快速发展的走廊地带的首要开发机会。地处宁静的菠萝林与私人庄园之中，周边分布着高档泳池别墅项目。地势平坦且紧邻高标准水泥路，非常适合各种高价值项目。从精品健康理疗中心到现代物流枢纽，甚至是专业的康养社区，这项资产已为动工做好准备。直接从业主处购买，享受无中介的精简交易。",
    "stat_room_title": "总面积",
    "stat_room_desc": "6 莱 (9,600 平方米)",
    "stat_scale_title": "法律地位",
    "stat_scale_desc": "Chanote (红翅鸟 N.S. 4 J.)",
    "stat_loc_title": "土地规划",
    "stat_loc_desc": "支持多样化开发",
    "stat_width_title": "沿街宽度",
    "stat_width_desc": "紧邻公共道路",
    "price_amount": "฿20,000,000 泰铢",
    "value_main_title": "投资亮点",
    "value_main_subtitle": "通过可立即使用且具有长期增值潜力的房产最大化您的投资回报。",
    "value_live_1_str": "卓越的交通连接：",
    "value_live_1_desc": "战略位置紧邻主要运输路线，确保物流效率。",
    "value_live_2_str": "安全的产权：",
    "value_live_2_desc": "清晣的红翅鸟产权证确保法律确定性和便捷的融资转换。",
    "value_live_3_str": "即刻动工地势：",
    "value_live_3_desc": "天然平坦的土地节省了昂贵的填土或复杂的平整工程费用。",
    "feat_main_title": "核心基础设施",
    "feat_main_subtitle": "该地块具备简化开发流程的基本特征。",
    "feat_pool_title": "广阔地块",
    "feat_pool_desc": "6 莱的广阔面积为大型开发项目提供无限的设计灵活性。",
    "feat_gym_title": "基础设施连接",
    "feat_gym_desc": "紧邻高标准水泥路，为施工和未来运营提供无缝物流支持。",
    "feat_walk_title": "高价值环境",
    "feat_walk_desc": "位于宁静但不断发展的地区，平衡了隐私与城市便利。",
    "feat_peace_title": "水电设施",
    "feat_peace_desc": "附近有水电接入口，缩短了报装时间。",
    "feat_park_title": "边界清晰",
    "feat_park_desc": "最新的测绘标记确认了准确边界，确保无侵占问题。",
    "feat_sec_title": "低开发成本",
    "feat_sec_desc": "无需大规模清理或土地修正即可立即启动项目。",
    "loc_condo_name": "华欣战略土地",
    "loc_condo_addr": "华欣, 班武里府 77110",
    "loc_condo_desc": "位于增长走廊，连接豪华生活与实用功能。",
    "loc_card1_title": "华欣海滨",
    "loc_card1_desc": "维持该地区持续需求的主要旅游驱动力。",
    "loc_card1_dist": "约 15 分钟车程",
    "loc_card2_title": "商业中心",
    "loc_card2_desc": "靠近城市设施、市场和行政中心。",
    "loc_card2_dist": "约 12 分钟车程",
    "loc_card3_title": "娱乐休闲",
    "loc_card3_desc": "周围环绕着世界一流的高尔夫球场和家庭休闲景点。",
    "loc_card3_dist": "约 5 分钟车程",
    "loc_card4_title": "生活零售",
    "loc_card4_desc": "轻松前往高档购物中心和国际餐饮。",
    "loc_card4_dist": "约 15 分钟车程",
    "loc_card5_title": "交通枢纽",
    "loc_card5_desc": "靠近华欣机场和区域交通走廊。",
    "loc_card5_dist": "约 25 分钟车程",
    "loc_card6_title": "家庭娱乐",
    "loc_card6_desc": "亚洲领先的水上丛林和户外活动所在地。",
    "loc_card6_dist": "约 20 分钟车程",
    "loc_card7_title": "卓越医疗",
    "loc_card7_desc": "距离顶级国际医疗机构仅几分钟路程。",
    "loc_card7_dist": "约 20 分钟车程",
    "loc_card8_title": "主要路口/零售",
    "loc_card8_desc": "连接曼谷的主干线上的战略地标。",
    "loc_card8_dist": "约 25 分钟车程",
    "loc_main_subtitle": "战略定位，充分利用华欣不断扩张的基础设施和旅游市场。",
    "gal_flt_bld": "土地资产",
    "gal_flt_liv": "地图规划",
    "gal_flt_fac": "交通连通",
    "video_section_title": "航拍视角",
    "video_section_subtitle": "通过无人机航拍画面感受这块 6 莱资产的规模与潜力。",
    "potential_title": "高收益开发潜力",
    "potential_subtitle": "为灵活度而设计，这块土地支持各种 high-value 开发模式。",
    "pot_resort_title": "酒店与康养",
    "pot_resort_desc": "在宁静的环境中设计一个精品度假村、专业康养中心或养老社区。",
    "pot_housing_title": "住宅社区",
    "pot_housing_desc": "理想的成熟住宅区、豪华别墅或私人度假屋群。",
    "pot_warehouse_title": "物流与仓储",
    "pot_warehouse_desc": "利用便捷的交通，打造智慧仓储或配送中心。",
    "pot_factory_title": "工业与商业",
    "pot_factory_desc": "专为轻工业制造或科技研发设施量身打造。",
    "contact_col_loc_desc": "6 莱战略地块<br>华欣, 班武里府"
  },
  "ja": {
    "hero_subtitle": "ホアヒンの急速な成長エリアに位置する 6 ライの土地の戦略的投資機会",
    "featured_title": "最高の開発用地",
    "featured_subtitle": "ラグジュアリーリゾート、住宅団地、または工業施設に最適な、希少な 6 ライのチャンノート（土地権利証）付き土地。",
    "about_title": "戦略的投資資産",
    "about_desc": "急速に進化するホアヒン回廊に位置するこの広大な 6 ライ（9,600 平方メートル）の土地は、最高の開発機会を提供します。パイナップル畑やプライベート邸宅、高級プールヴィラプロジェクトに囲まれた静かな環境で、多様な高価値プロジェクトに最適化されています。平坦な地形と高品質なコンクリート道路へのアクセスが特徴で、ブティック・ウェルネス・リトリートから現代的な物流拠点、さらには高齢者ケア施設やシニア向け住宅地まで、あらゆるニーズに対応可能です。オーナーから直接購入することで、合理的な取引が可能です。",
    "stat_room_title": "総面積",
    "stat_room_desc": "6 ライ (9,600 sq.m.)",
    "stat_scale_title": "法的ステータス",
    "stat_scale_desc": "チャンノート (赤ガルーダ N.S. 4 J.)",
    "stat_loc_title": "用途地域",
    "stat_loc_desc": "多様な開発をサポート",
    "stat_width_title": "接道幅",
    "stat_width_desc": "公道に隣接",
    "price_amount": "฿20,000,000 THB",
    "value_main_title": "投資ハイライト",
    "value_main_subtitle": "即利用可能で長期的な価値上昇が期待できる物件で、投資収益を最大化してください。",
    "value_live_1_str": "優れた交通網：",
    "value_live_1_desc": "主要な交通ルートへの接続が良好な戦略的立地で、物流の効率を確保。",
    "value_live_2_str": "安心の所有権：",
    "value_live_2_desc": "明確な赤ガルーダ土地権利証により、法的確実性とスムーズな融資移行を保証します。",
    "value_live_3_str": "建設準備完了：",
    "value_live_3_desc": "自然に平坦な土地のため、高額な盛り土や複雑な整地作業を削減できます。",
    "feat_main_title": "主要インフラ",
    "feat_main_subtitle": "開発プロセスを簡素化する不可欠な機能を備えています。",
    "feat_pool_title": "広大な区画",
    "feat_pool_desc": "大規模開発に無限のデザイン柔軟性を提供する、十分な 6 ライの敷地面積。",
    "feat_gym_title": "インフラへのアクセス",
    "feat_gym_desc": "公道のコンクリート道路に面しており、建設や将来の運営のための物流がスムーズです。",
    "feat_walk_title": "高価値な環境",
    "feat_walk_desc": "静かながら発展しつつあるエリアに位置し、プライバシーと都市の利便性を両立。",
    "feat_peace_title": "インフラ供給",
    "feat_peace_desc": "電気と水の接続ポイントが近くにあり、サービス開始までの期間を短縮できます。",
    "feat_park_title": "明確な境界",
    "feat_park_desc": "最新の測量マーカーにより正確な境界線を確認済みで、侵害の心配はありません。",
    "feat_sec_title": "低準備コスト",
    "feat_sec_desc": "大規模な造成や土地修正を必要とせず、即座にプロジェクトをキックオフ可能です。",
    "loc_condo_name": "戦略的なホアヒンの土地",
    "loc_condo_addr": "ホアヒン, プラチュアップキーリーカーン 77111",
    "loc_condo_desc": "成長エリアに位置し、ラグジュアリーな生活と機能性を両立。",
    "loc_card1_title": "ホアヒン・ビーチサイド",
    "loc_card1_desc": "エリア内の安定した需要を支える主要な観光拠。",
    "loc_card1_dist": "車で約 15 分",
    "loc_card2_title": "商圏中心部",
    "loc_card2_desc": "都市施設、マーケット、行政センターに近接した好立地。",
    "loc_card2_dist": "車で約 12 分",
    "loc_card3_title": "レクリエーション＆レジャー",
    "loc_card3_desc": "世界クラスのゴルフコースや家族向けアトラクションに囲まれています。",
    "loc_card3_dist": "車で約 5 分",
    "loc_card4_title": "ライフスタイル小売",
    "loc_card4_desc": "プレミアムなショッピングモールや国際的なレストランへ簡単にアクセス。",
    "loc_card4_dist": "車で約 15 分",
    "loc_card5_title": "交通アクセス",
    "loc_card5_desc": "ホアヒン空港や地域の主要な交通回廊に至近。",
    "loc_card5_dist": "車で約 25 分",
    "loc_card6_title": "家族向けエンターテインメント",
    "loc_card6_desc": "アジア有数のウォータージャングルやアウトドア活動の拠点。",
    "loc_card6_dist": "車で約 20 分",
    "loc_card7_title": "優れた医療施設",
    "loc_card7_desc": "トップクラスの国際的な医療機関からわずか数分の距離。",
    "loc_card7_dist": "車で約 20 分",
    "loc_card8_title": "主要ジャンクション/小売",
    "loc_card8_desc": "バンコクと結ぶ主要幹線道路沿いの戦略的なランドマーク。",
    "loc_card8_dist": "車で約 25 分",
    "loc_main_subtitle": "ホアヒンの拡大するインフラと観光需要を活用するための戦略的ポジション。",
    "gal_flt_bld": "土地遺産",
    "gal_flt_liv": "マッピング",
    "gal_flt_fac": "接続性",
    "video_section_title": "空中からの視点",
    "video_section_subtitle": "ドローン映像を通して、この 6 ライの資産の規模と可能性を体感してください。",
    "potential_title": "高収益開発の可能性",
    "potential_subtitle": "柔軟性を重視して設計されたこの土地は、多様な高価値開発モデルをサポートします。",
    "pot_resort_title": "ホスピタリティ＆ウェルネス",
    "pot_resort_desc": "静かな環境での隠れ家的なブティックリゾートや、専門的な高齢者ケア施設、シニア向け住宅地に最適です。",
    "pot_housing_title": "レジデンシャル・コミュニティ",
    "pot_housing_desc": "安全な住宅団地、豪華ヴィラ、または第二の拠点としてのプライベートクラスターに最適。",
    "pot_warehouse_title": "物流＆ストレージ",
    "pot_warehouse_desc": "接道の良さを活かしたスマートなストレージソリューションや配送センターに。",
    "pot_factory_title": "工業＆商業",
    "pot_factory_desc": "軽工業の製造や技術対応の工業施設に合わせたカスタマイズが可能。",
    "contact_col_loc_desc": "6 ライ 戦略的土地<br>ホアヒン, プラチュアップキーリーカーン"
  },
  "ko": {
    "hero_subtitle": "후아힌의 급성장 구역에 위치한 6라이 토지의 전략적 투자 기회",
    "featured_title": "프라임 개발 토지",
    "featured_subtitle": "고급 리조트, 주거 단지 또는 산업 시설에 적합한 Chanote 문서 포함 6라이 토지.",
    "about_title": "전략적 투자 자산",
    "about_desc": "급변하는 후아힌 통로에 위치한 이 방대한 6라이(9,600sqm) 토지는 최고의 개발 기회를 제공합니다. 파인애플 농장과 개인 저택, 인근의 럭셔리 풀 빌라 프로젝트들이 어우러진 평화로운 분위기 속에 위치하며, 다양한 고부가가치 프로젝트에 최적화되어 있습니다. 평탄한 지평과 즉각적인 콘크리트 도로 접근성을 갖추어 부티크 웰니스 단지부터 현대적인 물류 허브, 전문 요양 시설 또는 은퇴자 마을까지 즉시 건설이 가능합니다. 소유주 직거래로 간소화된 거래를 진행하세요.",
    "stat_room_title": "총 면적",
    "stat_room_desc": "6 라이 (9,600 sq.m.)",
    "stat_scale_title": "법적 상태",
    "stat_scale_desc": "Chanote (레드 가루다 N.S. 4 J.)",
    "stat_loc_title": "용도 구역",
    "stat_loc_desc": "다양한 개발 지원",
    "stat_width_title": "도로 전면",
    "stat_width_desc": "공도에 인접",
    "price_amount": "฿20,000,000 THB",
    "value_main_title": "투자 핵심 요소",
    "value_main_subtitle": "즉시 사용할 수 있고 장기적인 가치 상승이 가능한 부동산으로 투자 수익을 극대화하십시오.",
    "value_live_1_str": "우수한 연결성：",
    "value_live_1_desc": "주요 운송 경로와 연결된 전략적 위치로 물류 효율성을 보장합니다.",
    "value_live_2_str": "안전한 소유권：",
    "value_live_2_desc": "명확한 레드 가루다 토지 권리증은 법적 확실성과 원활한 대출 전환을 보장합니다.",
    "value_live_3_str": "건설 준비 완료 지형：", Korean: "자연적으로 평탄한 토지로 고가의 성토 작업이나 복잡한 정지 작업 비용을 절감할 수 있습니다.",
    "value_live_3_desc": "자연스럽게 평평한 지형으로 고가의 매립이나 복잡한 정지 작업 비용을 절감할 수 있습니다.",
    "feat_main_title": "핵심 인프라",
    "feat_main_subtitle": "개발 프로세스를 단순화하는 필수적인 기능들을 갖추고 있습니다.",
    "feat_pool_title": "광활한 부지",
    "feat_pool_desc": "대규모 개발을 위해 무한한 설계 유연성을 제공하는 6라이의 대규모 면적.",
    "feat_gym_title": "인프라 접근성",
    "feat_gym_desc": "품질 좋은 콘크리트 공도와 접해 있어 건설 및 향후 운영을 위한 물류 이동이 원활함.",
    "feat_walk_title": "고부가가치 환경",
    "feat_walk_desc": "조용하면서도 개발 중인 지역에 위치하여 프라이버시와 도시의 편리함 공존.",
    "feat_peace_title": "유틸리티 통합",
    "feat_peace_desc": "전기와 수도 인입 지점이 근처에 있어 서비스 연결 대기 시간을 단축할 수 있습니다.",
    "feat_park_title": "명확한 경계",
    "feat_park_desc": "최근 측량된 지점들이 정확한 경계를 확인해주며, 침범 문제가 없음을 보장합니다.",
    "feat_sec_title": "낮은 준비 비용",
    "feat_sec_desc": "대규모 정지 작업이나 부지 개선 없이 즉각적인 프로젝트 착수가 가능합니다.",
    "loc_condo_name": "전략적 후아힌 토지",
    "loc_condo_addr": "후아힌, 프라추압키리칸 77110",
    "loc_condo_desc": "성장 가도에 위치하여 럭셔리한 생활과 기능적 효율성을 연결합니다.",
    "loc_card1_title": "후아힌 해변가",
    "loc_card1_desc": "지역 내 지속적인 수요를 유지하는 주요 관광 동력.",
    "loc_card1_dist": "차로 약 15분",
    "loc_card2_title": "상업 중심지",
    "loc_card2_desc": "시내 편의시설, 시장, 관공서와 인접한 편리한 위치.",
    "loc_card2_dist": "차로 약 12분",
    "loc_card3_title": "휴양 및 레저",
    "loc_card3_desc": "세계적인 수준의 골프장과 가족 지향적 명소들로 둘러싸임.",
    "loc_card3_dist": "차로 약 5분",
    "loc_card4_title": "라이프스타일 쇼핑",
    "loc_card4_desc": "프리미엄 쇼핑몰과 다양한 국제 식당가 이용 용이.",
    "loc_card4_dist": "차로 약 15분",
    "loc_card5_title": "교통 이용",
    "loc_card5_desc": "후아힌 공항 및 주요 지역 이동 통로와 인접.",
    "loc_card5_dist": "차로 약 25분",
    "loc_card6_title": "가족 엔터테인먼트",
    "loc_card6_desc": "아시아 최고의 워터 정글과 야외 활동의 중심지.",
    "loc_card6_dist": "차로 약 20분",
    "loc_card7_title": "최고급 의료 서비스",
    "loc_card7_desc": "수준 높은 국제 의료 시설까지 단 몇 분 거리.",
    "loc_card7_dist": "차로 약 20분",
    "loc_card8_title": "주요 분기점/쇼핑",
    "loc_card8_desc": "방콕과 연결되는 주요 도로상의 전략적 랜드마크.",
    "loc_card8_dist": "차로 약 25분",
    "loc_main_subtitle": "후아힌의 확장되는 인프라와 관광 시장을 활용하기 위한 전략적 위치.",
    "gal_flt_bld": "토지 자산",
    "gal_flt_liv": "모형 배치",
    "gal_flt_fac": "연결성",
    "video_section_title": "항공 영상",
    "video_section_subtitle": "드론 영상을 통해 이 6라이 자산의 규모와 잠재력을 경험해 보십시오.",
    "potential_title": "고수익 개발 잠재력",
    "potential_subtitle": "유연성을 고려해 설계된 이 토지는 다양한 고부가가치 개발 모델을 지원합니다.",
    "pot_resort_title": "환대 및 웰니스",
    "pot_resort_desc": "평화로운 환경의 프라이빗 부티크 리조트 또는 전문 요양 센터 및 은퇴자 마을 조성에 적합합니다.",
    "pot_housing_title": "주거 커뮤니티",
    "pot_housing_desc": "보안이 강화된 주거 단지, 고급 빌라 또는 독채 주거군에 이상적.",
    "pot_warehouse_title": "물류 및 창고",
    "pot_warehouse_desc": "도로 접근성을 활용한 스마트 보관 솔루션이나 유통 센터 구축에 적합.",
    "pot_factory_title": "산업 및 상업",
    "pot_factory_desc": "경공업 제조나 기술 기반 산업 시설에 맞춤형으로 조성 가능.",
    "contact_col_loc_desc": "6라이 전략적 토지<br>후아힌, 프라추압키리칸"
  },
  "lo": {
    "hero_subtitle": "ໂອກາດການລົງທຶນທາງຍຸດທະສາດໃນເນື້ອທີ່ 6 ໄຣ່ ໃນເຂດທີ່ມີການເຕີບໂຕໄວຂອງຫົວຫີນ",
    "featured_title": "ດິນເພື່ອການພັດທະນາຊັ້ນນຳ",
    "featured_subtitle": "ດິນຕອນຫາຍາກເນື້ອທີ່ 6 ໄຣ່ ພ້ອມໂສນົດຄຣຸດແດງ ເໝາະສົມທີ່ສຸດສຳລັບຣີສອດຫຼູ, ໝູ່ບ້ານຈັດສັນ ຫຼື ສິ່ງອຳນວຍຄວາມສະດວກທາງອຸດສາຫະກຳ.",
    "about_title": "ຊັບສິນການລົງທຶນທາງຍຸດທະສາດ",
    "about_desc": "ດິນເນື້ອທີ່ກວ້າງ 6 ໄຣ່ (9,600 ຕຣ.ມ.) ນີ້ແມ່ນໂອກາດທອງສຳລັບການພັດທະນາໃນເຂດທີ່ກຳລັງຂະຫຍາຍຕົວຂອງຫົວຫີນ. ທ່າມກາງບັນຍາກາດທີ່ງຽບສະຫງົບຂອງສວນສັບປະລົດ ແລະ ບ້ານພັກສ່ວນຕົວ ພ້ອມທັງມີໂຄງການພູລວິນລ່າຢູ່ໃກ້ຄຽງ, ດ້ວຍລັກສະນະດິນທີ່ພຽງດີ ແລະ ຕິດທາງຄອນກີດທັນທີ, ພື້ນທີ່ນີ້ໄດ້ຖືກປັບປຸງໃຫ້ເໝາະສຳລັບໂຄງການທີ່ມີມູນຄ່າສູງຫຼາກຫຼາຍປະເພດ ບໍ່ວ່າຈະເປັນສະຖານທີ່ພັກຜ່ອນເພື່ອສຸຂະພາບລະດັບພຣີມຽມ ສູນການແພດ ແລະ ສະຫວັດດີການຜູ້ສູງອາຍຸ ຫຼື ຄັງສິນຄ້າທີ່ທັນສະໄໝ. ຊື້ຂາຍໂດຍກົງຈາກເຈົ້າຂອງເພື່ອຄວາມສະດວກ.",
    "stat_room_title": "ເນື້ອທີ່ທັງໝົດ",
    "stat_room_desc": "6 ໄຣ່ (9,600 sq.m.)",
    "stat_scale_title": "ສະຖານະທາງກົດໝາຍ",
    "stat_scale_desc": "ໂສນົດ (ຄຣຸດແດງ ນ.ສ. 4 ຈ.)",
    "stat_loc_title": "ການກຳນົດຜັງເມືອງ",
    "stat_loc_desc": "ຮອງຮັບການພັດທະນາທີ່ຫຼາກຫຼາຍ",
    "stat_width_title": "ໜ້າກວ້າງຕິດທາງ",
    "stat_width_desc": "ຕິດທາງສາທາລະນະ",
    "price_amount": "฿20,000,000 THB",
    "value_main_title": "ຈຸດເດັ່ນຂອງນັກລົງທຶນ",
    "value_main_subtitle": "ເພີ່ມຜົນຕອບແທນຂອງທ່ານໃຫ້ສູງສຸດດ້ວຍຊັບສິນທີ່ພ້ອມນຳໃຊ້ທັນທີ ແລະ ມີມູນຄ່າເພີ່ມຂຶ້ນໃນໄລຍະຍາວ.",
    "value_live_1_str": "ການເຊື່ອມຕໍ່ທີ່ຍອດຢ້ຽມ:",
    "value_live_1_desc": "ຕັ້ງຢູ່ໃນທຳເລຍຸດທະສາດທີ່ເຊື່ອມຕໍ່ກັບເສັ້ນທາງຂົນສົ່ງຫຼັກ ຮັບປະກັນປະສິດທິພາບທາງໂລຈິສຕິກ.",
    "value_live_2_str": "ກຳມະສິດທີ່ປອດໄພ:",
    "value_live_2_desc": "ໂສນົດຄຣຸດແດງທີ່ຊັດເຈນ ຮັບປະກັນຄວາມຖືກຕ້ອງທາງກົດໝາຍ ແລະ ງ່າຍຕໍ່ການຂໍສິນເຊື່ອ.",
    "value_live_3_str": "ພື້ນທີ່ພ້ອມກໍ່ສ້າງ:",
    "value_live_3_desc": "ທີ່ດິນພຽງຕາມທຳມະຊາດ ຊ່ວຍປະຢັດຄ່າໃຊ້ຈ່າຍໃນການຖົມດິນ ຫຼື ການປັບລະດັບດິນທີ່ຫຍຸ້ງຍາກ.",
    "feat_main_title": "ພື້ນຖານໂຄງລ່າງຫຼັກ",
    "feat_main_subtitle": "ພື້ນທີ່ນີ້ມີຄຸນສົມບັດສຳຄັນທີ່ຊ່ວຍໃຫ້ຂະບວນການພັດທະນາງ່າຍຂຶ້ນ.",
    "feat_pool_title": "ດິນຕອນໃຫຍ່",
    "feat_pool_desc": "ພື້ນທີ່ 6 ໄຣ່ທີ່ກວ້າງຂວາງ ໃຫ້ຄວາມຢືດຢຸ່ນບໍ່ຈຳກັດໃນການອອກແບບສຳລັບໂຄງການໃຫຍ່.",
    "feat_gym_title": "ເຂົ້າເຖິງສາທາລະນູປະໂພກ",
    "feat_gym_desc": "ຕິດທາງຄອນກີດສາທາລະນະ ໃຫ້ຄວາມສະດວກໃນການຂົນສົ່ງສຳລັບວຽກກໍ່ສ້າງ ແລະ ການດຳເນີນງານ.",
    "feat_walk_title": "ສະພາບແວດລ້ອມມູນຄ່າສູງ",
    "feat_walk_desc": "ຢູ່ໃນພື້ນທີ່ທີ່ງຽບສະຫງົບແຕ່ກຳລັງພັດທະນາ ໃຫ້ຄວາມລົງຕົວລະຫວ່າງຄວາມເປັນສ່ວນຕົວ ແລະ ຄວາມສະດວກສະບາຍ.",
    "feat_peace_title": "ລະບົບພື້ນຖານພ້ອມ",
    "feat_peace_desc": "ລະບົບໄຟຟ້າ ແລະ ນ້ຳປະປາເຂົ້າເຖິງພື້ນທີ່ ຊ່ວຍຫຼຸດໄລຍະເວລາໃນການຂໍໃຊ້ບໍລິການ.",
    "feat_park_title": "ແນວເຂດຊັດເຈນ",
    "feat_park_desc": "ຜ່ານການວັດແທກຫຼ້າສຸດ ຢືນຢັນແນວເຂດທີ່ຖືກຕ້ອງ ໝັ້ນໃຈບໍ່ມີບັນຫາການບຸກລຸກ.",
    "feat_sec_title": "ຄ່າກະກຽມພື້ນທີ່ຕ່ຳ",
    "feat_sec_desc": "ດິນພ້ອມໃຊ້ງານທັນທີ ບໍ່ຕ້ອງມີວຽກປັບສະພາບດິນທີ່ຍາກ ສາມາດເລີ່ມວຽກພື້ນຖານໄດ້ເລີຍ.",
    "loc_condo_name": "ດິນຍຸດທະສາດ ຫົວຫີນ",
    "loc_condo_addr": "ຫົວຫີນ, ປະຈວບຄີຣີຂັນ 77110",
    "loc_condo_desc": "ຕັ້ງຢູ່ໃນທຳເລສັກກະຍະພາບຂອງການພັດທະນາ ເຊື່ອມຕໍ່ຄວາມຫຼູຫຼາ ແລະ ການໃຊ້ງານໄດ້ຢ່າງລົງຕົວ.",
    "loc_card1_title": "ຊາຍຫາດຫົວຫີນ",
    "loc_card1_desc": "ປັດໄຈຫຼັກຂັບເຄື່ອນການທ່ອງທ່ຽວທີ່ສ້າງຄວາມຕ້ອງການຢ່າງຕໍ່ເນື່ອງ.",
    "loc_card1_dist": "ຂັບລົດ ~15 ນາທີ",
    "loc_card2_title": "ສູນກາງທຸລະກິດ",
    "loc_card2_desc": "ຕັ້ງຢູ່ໃກ້ສິ່ງອຳນວຍຄວາມສະດວກໃນເມືອງ, ຕະຫຼາດ ແລະ ສູນລັດຖະການ.",
    "loc_card2_dist": "ຂັບລົດ ~12 ນາທີ",
    "loc_card3_title": "ການພັກຜ່ອນຢ່ອນໃຈ",
    "loc_card3_desc": "ລ້ອມຮອບດ້ວຍສະໜາມກອຟລະດັບໂລກ ແລະ ສະຖານທີ່ທ່ອງທ່ຽວຄອບຄົວ.",
    "loc_card3_dist": "ຂັບລົດ ~5 ນາທີ",
    "loc_card4_title": "ຫ້າງສັບພະສິນຄ້າ",
    "loc_card4_desc": "ເຂົ້າເຖິງແຫຼ່ງຊ້ອບປິ້ງລະດັບພຣີມຽມ ແລະ ຮ້ານອາຫານນານາຊາດ.",
    "loc_card4_dist": "ຂັບລົດ ~15 ນາທີ",
    "loc_card5_title": "ການຄົມມະນາຄົມ",
    "loc_card5_desc": "ໃກ້ສະໜາມບິນຫົວຫີນ ແລະ ເສັ້ນທາງຄົມມະນາຄົມລະດັບພາກພື້ນ.",
    "loc_card5_dist": "ຂັບລົດ ~25 ນາທີ",
    "loc_card6_title": "ຄວາມບັນເທີງຄອບຄົວ",
    "loc_card6_desc": "ແຫຼ່ງລວມສວນນ້ຳຊັ້ນນຳ ແລະ ກິດຈະກຳກາງແຈ້ງທີ່ຍອດນິຍົມ.",
    "loc_card6_dist": "ຂັບລົດ ~20 ນາທີ",
    "loc_card7_title": "ການແພດຊັ້ນນຳ",
    "loc_card7_desc": "ໃກ້ໂຮງໝໍລະດັບນານາຊາດຊັ້ນນຳໃນພື້ນທີ່.",
    "loc_card7_dist": "ຂັບລົດ ~20 ນາທີ",
    "loc_card8_title": "ຈຸດພັກລົດຫຼັກ",
    "loc_card8_desc": "ຈຸດແລນມາກສຳຄັນເທິງເສັ້ນທາງຫຼັກທີ່ເຊື່ອມຕໍ່ຫາບາງກອກ.",
    "loc_card8_dist": "ຂັບລົດ ~25 ນາທີ",
    "loc_main_subtitle": "ວາງຕຳແໜ່ງຢ່າງເໝາະສົມເພື່ອຮັບຜົນປະໂຫຍດຈາກການຂະຫຍາຍຕົວຂອງຫົວຫີນ.",
    "gal_flt_bld": "ຊັບສິນດິນ",
    "gal_flt_liv": "ແຜນທີ່",
    "gal_flt_fac": "ການເຊື່ອມຕໍ່",
    "video_section_title": "ຂໍ້ມູນແບບມຸມສູງ",
    "video_section_subtitle": "ສຳຜັດສັກກະຍະພາບ ແລະ ຂະໜາດຂອງດິນຜ່ານມຸມມອງໂດຣນ.",
    "potential_title": "ສັກກະຍະພາບການພັດທະນາທີ່ໃຫ້ຜົນຕອບແທນສູງ",
    "potential_subtitle": "ຖືກອອກແບບມາເພື່ອຄວາມຢືດຢຸ່ນ, ດິນຕອນນີ້ຮອງຮັບການພັດທະນາຫຼາຍຮູບແບບ.",
    "pot_resort_title": "ການບໍລິການ ແລະ ສຸຂະພາບ",
    "pot_resort_desc": "ເໝາະສຳລັບການພັດທະນາບູທີຄຣີສອດ ສູນເບິ່ງແຍງຜູ້ສູງອາຍຸແບບຄົບວົງຈອນ ຫຼື ໝູ່ບ້ານພັກຜ່ອນທີ່ງຽບສະຫງົບ.",
    "pot_housing_title": "ຊຸມຊົນທີ່ຢູ່ອາໄສ",
    "pot_housing_desc": "ເໝາະສຳລັບໂຄງການບ້ານຈັດສັນ, ວິນລ່າຫຼູ ຫຼື ບ້ານພັກຕາກອາກາດ.",
    "pot_warehouse_title": "ໂລຈິສຕິກ ແລະ ສາງສິນຄ້າ",
    "pot_warehouse_desc": "ໃຊ້ປະໂຫຍດຈາກການເຂົ້າເຖິງທາງເພື່ອສ້າງສາງສິນຄ້າທີ່ທັນສະໄໝ.",
    "pot_factory_title": "ອຸດສາຫະກຳ",
    "pot_factory_desc": "ອອກແບບມາເປັນພິເສດສຳລັບການຜະລິດອຸດສາຫະກຳເບົາ ຫຼື ສິ່ງອຳນວຍຄວາມສະດວກດ້ານເຕັກໂນໂລຢີ.",
    "contact_col_loc_desc": "ດິນຍຸດທະສາດ 6 ໄຣ່<br>ຫົວຫີນ, ປະຈວບຄີຣີຂັນ"
  }
};

var propertyBasePath = "";

var propertyCategory = "Land";

var propertyGallery = [
    { src: "land/dji_fly_20260415_095936_0016_1776239662408_photo_beautify.webp", category: "land" },
    { src: "land/f1.webp", category: "land" },
    { src: "land/f2.webp", category: "land" },
    { src: "land/f3.webp", category: "land" },
    { src: "land/f4.webp", category: "land" },
    { src: "land/f5.webp", category: "land" },
    { src: "land/f6.webp", category: "land" },
    { src: "map/map1.webp", category: "map" },
    { src: "nearby/nearby_1.webp", category: "nearby" },
    { src: "nearby/nearby_2.webp", category: "nearby" },
    { src: "nearby/nearby_3.webp", category: "nearby" },
    { src: "nearby/nearby_4.webp", category: "nearby" },
    { src: "nearby/nearby_5.webp", category: "nearby" }
];
