var propertyContent = {
  "en": {
    "hero_subtitle": "Strategic 6-Rai Investment Opportunity in Hua Hin's High-Growth Zone.",
    "featured_title": "Prime Development Land",
    "featured_subtitle": "A rare 6-Rai parcel with full Chanote title, perfectly positioned for luxury resorts, residential estates, or industrial facilities.",
    "about_title": "Strategic Investment Asset",
    "about_desc": "This expansive 6-Rai (9,600 sqm) parcel of land represents a premier development opportunity in the rapidly evolving Hua Hin corridor. Characterized by flat topography and immediate concrete road accessibility, the site is optimized for diverse high-value projects. The property is surrounded by a peaceful neighborhood including private houses, pool villa villages, pineapple farms, and housing estates. Acquire directly from the owner for a streamlined, agency-free transaction.",
    "stat_room_title": "Total Area",
    "stat_room_desc": "6 Rai (9,600 sq.m.)",
    "stat_scale_title": "Legal Status",
    "stat_scale_desc": "Chanote (Red Garuda)",
    "stat_loc_title": "Zoning",
    "stat_loc_desc": "Multi-Purpose Development",
    "stat_width_title": "Road Frontage",
    "stat_width_desc": "Wide Public Access",
    "price_amount": "฿20,000,000 THB",
    "value_main_title": "Investor Highlights",
    "value_main_subtitle": "Maximize your ROI with a property that offers both immediate utility and long-term equity growth.",
    "value_live_1_str": "Premium Connectivity:",
    "value_live_1_desc": "Strategically located with direct access to main transit routes, ensuring logistical efficiency.",
    "value_live_2_str": "Secure Ownership:",
    "value_live_2_desc": "Full Chanote title deed (Nor Sor 4 Jor) ensures absolute legal certainty and ease of financing.",
    "value_live_3_str": "Build-Ready Terrain:",
    "value_live_3_desc": "Naturally flat ground eliminates the need for expensive soil filling or complex site leveling.",
    "value_inv_1_str": "Capital Growth:",
    "value_inv_1_desc": "Situated in a high-appreciation zone fueled by local infrastructure and tourism expansion.",
    "value_inv_2_str": "Operational Versatility:",
    "value_inv_2_desc": "Suitable for a broad spectrum of uses: Luxury Villas, Private Estates, or Modern Warehousing.",
    "value_inv_3_str": "Owner Direct Listing:",
    "value_inv_3_desc": "Transparent pricing and direct communication with the owner for a frictionless acquisition.",
    "feat_pool_title": "Expansive Plot",
    "feat_pool_desc": "A substantial 6-Rai footprint providing limitless design flexibility for large-scale developments.",
    "feat_gym_title": "Concrete Road Access",
    "feat_gym_desc": "Bordered by a public concrete road, offering seamless logistics for construction and future operations.",
    "feat_walk_title": "High-Value Setting",
    "feat_walk_desc": "Positioned in a tranquil yet developing area, balancing privacy with urban convenience.",
    "feat_peace_title": "Utility Integration",
    "feat_peace_desc": "Electricity and water mains are readily accessible, significantly reducing development lead times.",
    "feat_park_title": "Surveyed Boundaries",
    "feat_park_desc": "Current surveys confirm precise property lines, ensuring zero encroachment issues.",
    "feat_sec_title": "Low Site Cost",
    "feat_sec_desc": "Minimal site clearing required; the land is ready for immediate foundation work.",
    "loc_condo_name": "Hua Hin Strategic Land",
    "loc_condo_addr": "Hua Hin, Prachuap Khiri Khan 77110",
    "loc_condo_desc": "Optimally located in a development hotspot, bridging the gap between coastal luxury and commercial utility.",
    "loc_card1_title": "Hua Hin Beachside",
    "loc_card1_desc": "A major tourism driver providing steady demand for hospitality projects.",
    "loc_card1_dist": "~15 Mins Drive",
    "loc_card2_title": "Commercial Hub",
    "loc_card2_desc": "Close proximity to city amenities, markets, and administrative centers.",
    "loc_card2_dist": "~12 Mins Drive",
    "loc_card3_title": "Recreation & Leisure",
    "loc_card3_desc": "Surrounded by world-class golf courses and family-oriented attractions.",
    "loc_card3_dist": "~5 Mins Drive",
    "loc_card4_title": "Lifestyle Retail",
    "loc_card4_desc": "Easy access to premium shopping malls and international dining.",
    "loc_card4_dist": "~15 Mins Drive",
    "loc_card5_title": "Transport Access",
    "loc_card5_desc": "Near Hua Hin Airport and regional transit corridors.",
    "loc_card5_dist": "~25 Mins Drive",
    "loc_card6_title": "Family Entertainment",
    "loc_card6_desc": "Home to Asia's leading water jungle and outdoor activities.",
    "loc_card6_dist": "~20 Mins Drive",
    "loc_card7_title": "Medical Excellence",
    "loc_card7_desc": "Minutes away from top-tier international healthcare facilities.",
    "loc_card7_dist": "~20 Mins Drive",
    "loc_card8_title": "Major Junction/Retail",
    "loc_card8_desc": "A strategic landmark on the main artery connecting to Bangkok.",
    "loc_card8_dist": "~25 Mins Drive",
    "loc_main_subtitle": "Strategically positioned to leverage Hua Hin's expanding infrastructure and tourism reach.",
    "gal_flt_bld": "Land Assets",
    "gal_flt_liv": "Mapping",
    "gal_flt_fac": "Connectivity",
    "video_section_title": "Aerial Site Insights",
    "video_section_subtitle": "A comprehensive drone perspective of the plot's scale and strategic surroundings.",
    "potential_title": "High-Yield Development Potential",
    "potential_subtitle": "Engineered for flexibility, this land supports various high-value development models.",
    "pot_resort_title": "Hospitality & Wellness",
    "pot_resort_desc": "Design a secluded boutique resort, wellness sanctuary, elderly care center, or retirement village in a peaceful environment.",
    "pot_housing_title": "Residential Communities",
    "pot_housing_desc": "Ideal for a secure housing estate, luxury villas, or a private cluster of second homes.",
    "pot_warehouse_title": "Logistics & Storage",
    "pot_warehouse_desc": "Leverage road accessibility for smart storage solutions or distribution centers.",
    "pot_factory_title": "Commercial Industrial",
    "pot_factory_desc": "Tailor-made for light manufacturing or tech-ready industrial facilities.",
    "contact_col_loc_desc": "6-Rai Strategic Land<br>Hua Hin, Prachuap Khiri Khan"
  },
  "th": {
    "hero_subtitle": "โอกาสการลงทุนเชิงกลยุทธบนที่ดิน 6 ไร่ ในโซนที่มีการเติบโตสูงของหัวหิน",
    "featured_title": "ที่ดินเพื่อการพัฒนา ทำเลทอง",
    "featured_subtitle": "เนื้อที่ 6 ไร่ พร้อมโฉนดครุฑแดง เหมาะอย่างยิ่งสำหรับรีสอร์ทหรู โครงการหมู่บ้าน หรืออาคารพาณิชย์และโกดัง",
    "about_title": "สินทรัพย์เพื่อการลงทุนเชิงกลยุทธ์",
    "about_desc": "ที่ดินผืนใหญ่ขนาด 6 ไร่ (9,600 ตร.ม.) นี้เป็นโอกาสทองสำหรับการพัฒนาในระเบียงเศรษฐกิจที่กำลังเติบโตของหัวหิน ด้วยลักษณะภูมิประเทศที่ราบเรียบและติดถนนคอนกรีตสาธารณะ พื้นที่นี้ได้รับการปรับปรุงให้เหมาะสำหรับโครงการที่มีมูลค่าสูง แวดล้อมไปด้วยเพื่อนบ้านที่เงียบสงบ ทั้งบ้านเดี่ยว หมู่บ้านพูลวิลล่า ไร่สับปะรด และหมู่บ้านจัดสรร ซื้อขายโดยตรงจากเจ้าของเพื่อความรวดเร็วและประหยัดค่านายหน้า",
    "stat_room_title": "เนื้อที่ทั้งหมด",
    "stat_room_desc": "6 ไร่ (9,600 ตร.ม.)",
    "stat_scale_title": "สถานะทางกฎหมาย",
    "stat_scale_desc": "โฉนด (ครุฑแดง น.ส. 4 จ.)",
    "stat_loc_title": "ผังเมือง",
    "stat_loc_desc": "รองรับการพัฒนาที่หลากหลาย",
    "stat_width_title": "หน้ากว้างถนน",
    "stat_width_desc": "ติดทางสาธารณะกว้าง",
    "price_amount": "฿20,000,000 บาท",
    "value_main_title": "จุดเด่นสำหรับนักลงทุน",
    "value_main_subtitle": "เพิ่มผลตอบแทนสูงสุดด้วยอสังหาริมทรัพย์ที่พร้อมใช้งานทันทีและมีมูลค่าเพิ่มขึ้นในระยะยาว",
    "value_live_1_str": "การเชื่อมต่อที่ยอดเยี่ยม:",
    "value_live_1_desc": "ตั้งอยู่ในทำเลเชิงกลยุทธ์ที่เชื่อมต่อกับเส้นทางคมนาคมหลัก มั่นใจได้ในประสิทธิภาพด้านการขนส่ง",
    "value_live_2_str": "กรรมสิทธิ์ที่ปลอดภัย:",
    "value_live_2_desc": "โฉนดที่ดินครุฑแดงที่ชัดเจน มั่นใจได้ในความถูกต้องตามกฎหมายและง่ายต่อการขอสินเชื่อ",
    "value_live_3_str": "พื้นที่พร้อมก่อสร้าง:",
    "value_live_3_desc": "ที่ดินที่ราบเรียบตามธรรมชาติช่วยประหยัดค่าใช้จ่ายในการถมที่หรือการปรับระดับพื้นที่ที่ยุ่งยาก",
    "value_inv_1_str": "การเติบโตของเงินทุน:",
    "value_inv_1_desc": "อยู่ในโซนที่มีมูลค่าเพิ่มสูงอย่างต่อเนื่อง ด้วยแรงหนุนจากโครงสร้างพื้นฐานและการขยายตัวของการท่องเที่ยว",
    "value_inv_2_str": "การใช้งานที่หลากหลาย:",
    "value_inv_2_desc": "เหมาะสำหรับการใช้งานที่กว้างขวาง เช่น วิลล่าหรู โครงการบ้านจัดสรร หรือคลังสินค้าที่ทันสมัย",
    "value_inv_3_str": "ติดต่อเจ้าของโดยตรง:",
    "value_inv_3_desc": "ราคาโปร่งใสและการสื่อสารโดยตรงกับเจ้าของ เพื่อขั้นตอนการซื้อขายที่ราบรื่นไร้อุปสรรค",
    "feat_pool_title": "ที่ดินผืนใหญ่",
    "feat_pool_desc": "พื้นที่ 6 ไร่ที่กว้างขวาง มอบความยืดหยุ่นไร้ขีดจำกัดในการออกแบบสำหรับโครงการขนาดใหญ่",
    "feat_gym_title": "ติดถนนคอนกรีต",
    "feat_gym_desc": "ติดถนนสาธารณะคอนกรีต มอบความสะดวกในการขนส่งสำหรับงานก่อสร้างและการดำเนินงานในอนาคต",
    "feat_walk_title": "สภาพแวดล้อมมูลค่าสูง",
    "feat_walk_desc": "อยู่ในพื้นที่ที่เงียบสงบแต่กำลังพัฒนา ให้ความลงตัวระหว่างความเป็นส่วนตัวและความสะดวกสบาย",
    "feat_peace_title": "ระบบสาธารณูปโภคพร้อม",
    "feat_peace_desc": "ระบบไฟฟ้าและน้ำประปาเข้าถึงพื้นที่ ช่วยลดระยะเวลาและขั้นตอนในการขอใช้บริการได้มาก",
    "feat_park_title": "แนวเขตชัดเจน",
    "feat_park_desc": "ผ่านการรังวัดล่าสุด ยืนยันแนวเขตที่ดินที่ถูกต้องแม่นยำ มั่นใจได้ว่าไม่มีปัญหาการรุก้ำ",
    "feat_sec_title": "ค่าเตรียมพื้นที่ต่ำ",
    "feat_sec_desc": "ที่ดินพร้อมใช้งานทันที ไม่ต้องมีงานปรับสภาพดินที่ซับซ้อน สามารถเริ่มงานฐานรากได้ทันที",
    "loc_condo_name": "ที่ดินยุทธศาสตร์ หัวหิน",
    "loc_condo_addr": "หัวหิน ประจวบคีรีขันธ์ 77110",
    "loc_condo_desc": "ตั้งอยู่ในทำเลศักยภาพของการพัฒนา เชื่อมต่อความหรูหราริมทะเลและการใช้งานเชิงพาณิชย์ได้อย่างลงตัว",
    "loc_card1_title": "ชายหาดหัวหิน",
    "loc_card1_desc": "ปัจจัยหลักขับเคลื่อนการท่องเที่ยวที่สร้างความต้องการอย่างต่อเนื่องสำหรับโครงการด้านบริการ",
    "loc_card1_dist": "ขับรถ ~15 นาที",
    "loc_card2_title": "ศูนย์กลางธุรกิจ",
    "loc_card2_desc": "ตั้งอยู่ใกล้สิ่งอำนวยความสะดวกในเมือง ตลาด และศูนย์ราชการ",
    "loc_card2_dist": "ขับรถ ~12 นาที",
    "loc_card3_title": "สันทนาการและการพักผ่อน",
    "loc_card3_desc": "ล้อมรอบด้วยสนามกอล์ฟระดับโลกและสถานที่ท่องเที่ยวสำหรับครอบครัว",
    "loc_card3_dist": "ขับรถ ~5 นาที",
    "loc_card4_title": "ห้างสรรพสินค้าไลฟ์สไตล์",
    "loc_card4_desc": "เข้าถึงแหล่งช้อปปิ้งระดับพรีเมียมและร้านอาหารนานาชาติได้อย่างง่ายดาย",
    "loc_card4_dist": "ขับรถ ~15 นาที",
    "loc_card5_title": "การเข้าถึงการคมนาคม",
    "loc_card5_desc": "ใกล้สนามบินหัวหินและแนวเส้นทางคมนาคมระดับภูมิภาค",
    "loc_card5_dist": "ขับรถ ~25 นาที",
    "loc_card6_title": "ความบันเทิงสำหรับครอบครัว",
    "loc_card6_desc": "แหล่งรวมสวนน้ำชั้นนำและกิจกรรมกลางแจ้งที่เป็นที่นิยม",
    "loc_card6_dist": "ขับรถ ~20 นาที",
    "loc_card7_title": "การแพทย์ชั้นนำ",
    "loc_card7_desc": "ใกล้สถานพยาบาลระดับนานาชาติชั้นนำในพื้นที่",
    "loc_card7_dist": "ขับรถ ~20 นาที",
    "loc_card8_title": "จุดพักรถและแหล่งช้อปปิ้งหลัก",
    "loc_card8_desc": "จุดแลนด์มาร์คสำคัญบนถนนเส้นหลักที่เชื่อมต่อสู่กรุงเทพฯ",
    "loc_card8_dist": "ขับรถ ~25 นาที",
    "loc_main_subtitle": "วางตำแหน่งอย่างเหมาะสมเพื่อใช้ประโยชน์จากการขยายตัวของโครงสร้างพื้นฐานและการท่องเที่ยวของหัวหิน",
    "gal_flt_bld": "ทรัพย์สินที่ดิน",
    "gal_flt_liv": "การแผนที่",
    "gal_flt_fac": "การเชื่อมต่อ",
    "video_section_title": "ข้อมูลเชิงลึกจากภาพมุมสูง",
    "video_section_subtitle": "สัมผัสศักยภาพและขนาดของที่ดินผ่านมุมมองโดรนที่ครอบคลุมทุกมิติ",
    "potential_title": "ศักยภาพการพัฒนาที่ให้ผลตอบแทนสูง",
    "potential_subtitle": "ออกแบบมาเพื่อความยืดหยุ่น ที่ดินผืนนี้รองรับโมเดลการพัฒนาที่มีมูลค่าสูงหลากหลายประเภท",
    "pot_resort_title": "การบริการและสุขภาพ",
    "pot_resort_desc": "ออกแบบบูทีครีสอร์ท สถานพักผ่อนเพื่อสุขภาพ ศูนย์ดูแลผู้สูงอายุ หรือหมู่บ้านเกษียณอายุในสภาพแวดล้อมที่สงบ",
    "pot_housing_title": "ชุมชนที่อยู่อาศัย",
    "pot_housing_desc": "เหมาะสำหรับโครงการบ้านจัดสรร วิลล่าหรู หรือกลุ่มบ้านพักตากอากาศส่วนตัว",
    "pot_warehouse_title": "โลจิสติกส์และคลังสินค้า",
    "pot_warehouse_desc": "ใช้ประโยชน์จากการเข้าถึงถนนเพื่อสร้างโซลูชันคลังสินค้าที่ชาญฉลาดหรือศูนย์กระจายสินค้า",
    "pot_factory_title": "อุตสาหกรรมชิงพาณิชย์",
    "pot_factory_desc": "ออกแบบมาเฉพาะสำหรับการผลิตอุตสาหกรรมเบาหรือสิ่งอำนวยความสะดวกทางเทคโนโลยี",
    "contact_col_loc_desc": "ที่ดินยุทธศาสตร์ 6 ไร่<br>หัวหิน ประจวบคีรีขันธ์"
  },
  "zh": {
    "hero_subtitle": "在华欣快速增长区发现 6 莱战略投资机遇。",
    "featured_title": "顶级开发地块",
    "featured_subtitle": "稀有的 6 莱土地，拥有完整 Chanote 产权证，非常适合豪华度假村、住宅区或工业设施。",
    "about_title": "战略投资资产",
    "about_desc": "这块占地 6 莱（9,600 平方米）的土地代表了华欣快速发展的走廊地带的首要开发机会。地势平坦，连接公共混凝土道路，非常适合各种高价值项目。周围环境宁静，有私家别墅、泳池别墅群、菠萝园和住宅小区。直接从业主处购买，享受无中介的精简交易。",
    "stat_room_title": "总面积",
    "stat_room_desc": "6 莱 (9,600 平方米)",
    "stat_scale_title": "法律地位",
    "stat_scale_desc": "Chanote (红契)",
    "stat_loc_title": "规划用途",
    "stat_loc_desc": "多功能开发",
    "stat_width_title": "临路面宽",
    "stat_width_desc": "宽敞的公共通路",
    "price_amount": "฿20,000,000 泰铢",
    "value_main_title": "投资亮点",
    "value_main_subtitle": "通过具有即时实用性和长期资产增长潜力的物业实现投资回报最大化。",
    "value_live_1_str": "优质连通性：",
    "value_live_1_desc": "战略位置，可直接通往主要交通路线，确保物流效率。",
    "value_live_2_str": "安全所有权：",
    "value_live_2_desc": "完整的 Chanote 产权证（Nor Sor 4 Jor）确保绝对的法律确定性和融资便利。",
    "value_live_3_str": "即时施工地形：",
    "value_live_3_desc": "自然平坦的土地消除了昂贵的填土或复杂的场地平整需求。",
    "value_inv_1_str": "资本增长：",
    "value_inv_1_desc": "位于由当地基础设施和旅游扩张推动的高增值区。",
    "value_inv_2_str": "运营多样性：",
    "value_inv_2_desc": "适用于广泛的用途：豪华别墅、私人庄园或现代仓储。",
    "value_inv_3_str": "业主直接出售：",
    "value_inv_3_desc": "价格透明，直接与业主沟通，确保无障碍收购。",
    "feat_pool_title": "广阔地块",
    "feat_pool_desc": "6 莱的广阔面积为大型开发项目提供无限的设计灵活性。",
    "feat_gym_title": "混凝土道路连接",
    "feat_gym_desc": "紧邻公共混凝土道路，为施工和未来运营提供无缝物流支持。",
    "feat_walk_title": "高价值环境",
    "feat_walk_desc": "位于宁静但不断发展的地区，平衡了隐私与城市便利。",
    "feat_peace_title": "水电设施",
    "feat_peace_desc": "电力和供水总管随时可用，大幅缩短开发交付周期。",
    "feat_park_title": "已测量边界",
    "feat_park_desc": "最新的测量确认了精确的物业边界线，确保零侵权风险。",
    "feat_sec_title": "低场地成本",
    "feat_sec_desc": "仅需极少的场地清理，土地可立即开展地基工程。",
    "loc_condo_name": "华欣战略土地",
    "loc_condo_addr": "华欣，班武里府 77110",
    "loc_condo_desc": "地理位置优越，位于开发热点区，连接沿海豪华与商业实用性。",
    "loc_card1_title": "华欣海滨",
    "loc_card1_desc": "主要的旅游驱动力，为酒店项目提供稳定的需求。",
    "loc_card1_dist": "约 15 分钟车程",
    "loc_card2_title": "商业中心",
    "loc_card2_desc": "靠近城市设施、市场和行政中心。",
    "loc_card2_dist": "约 12 分钟车程",
    "loc_card3_title": "娱乐休闲",
    "loc_card3_desc": "周围环绕着世界一流的高尔夫球场和家庭休闲景点。",
    "loc_card3_dist": "约 5 分钟车程",
    "loc_card4_title": "生活零售",
    "loc_card4_desc": "轻松前往高档购物中心和国际餐饮。",
    "loc_card4_dist": "约 15 分钟车程",
    "loc_card5_title": "交通枢纽",
    "loc_card5_desc": "靠近华欣机场和区域交通走廊。",
    "loc_card5_dist": "约 25 分钟车程",
    "loc_card6_title": "家庭娱乐",
    "loc_card6_desc": "亚洲领先的水上丛林和户外活动所在地。",
    "loc_card6_dist": "约 20 分钟车程",
    "loc_card7_title": "卓越医疗",
    "loc_card7_desc": "距离顶级国际医疗机构仅几分钟路程。",
    "loc_card7_dist": "约 20 分钟车程",
    "loc_card8_title": "主要路口/零售",
    "loc_card8_desc": "连接曼谷的主干线上的战略地标。",
    "loc_card8_dist": "约 25 分钟车程",
    "loc_main_subtitle": "战略定位，充分利用华欣不断扩张的基础设施和旅游市场。",
    "gal_flt_bld": "土地资产",
    "gal_flt_liv": "地图规划",
    "gal_flt_fac": "交通连通",
    "video_section_title": "航拍现场洞察",
    "video_section_subtitle": "从无人机角度全面展示地块规模和战略环境。",
    "potential_title": "高收益开发潜力",
    "potential_subtitle": "为灵活度而设计，这块土地支持各种高价值开发模式。",
    "pot_resort_title": "酒店与康养",
    "pot_resort_desc": "在宁静的环境中设计僻静的精品度假村、健康理疗中心、养老院或退休村。",
    "pot_housing_title": "住宅社区",
    "pot_housing_desc": "理想的成熟住宅区、豪华别墅或私人度假屋群。",
    "pot_warehouse_title": "物流与仓储",
    "pot_warehouse_desc": "利用道路连通性打造智能存储解决方案或配送中心。",
    "pot_factory_title": "商用工业",
    "pot_factory_desc": "量身定制的轻工业制造或科技型工业设施。",
    "contact_col_loc_desc": "6 莱战略土地<br>华欣，班武里府"
  },
  "ja": {
    "hero_subtitle": "ホアヒンの高成長エリアにおける 6 ライの戦略的投資機会。",
    "featured_title": "開発用プライムランド",
    "featured_subtitle": "豪華リゾート、住宅地、または工業施設に最適な、フル Chanote 権利証付きの希少な 6 ライの土地。",
    "about_title": "戦略的投資資産",
    "about_desc": "急速に進化するホアヒン回廊に位置するこの広大な 6 ライ（9,600 平方メートル）の土地は、最高の開発機会を提供します。平坦な地形と公共のコンクリート道路への直接アクセスが特徴で、多様な高価値プロジェクトに最適化されています。周辺は静かな環境で、戸建て住宅、プールヴィラ、パイナップル畑、住宅地などがあります。オーナーから直接購入することで、仲介手数料なしの合理的な取引が可能です。",
    "stat_room_title": "総面積",
    "stat_room_desc": "6 ライ (9,600 平方メートル)",
    "stat_scale_title": "法的ステータス",
    "stat_scale_desc": "Chanote (赤ガルダ)",
    "stat_loc_title": "ゾーニング",
    "stat_loc_desc": "多目的開発",
    "stat_width_title": "前面道路幅",
    "stat_width_desc": "広い公道アクセス",
    "price_amount": "20,000,000 バーツ",
    "value_main_title": "投資ハイライト",
    "value_main_subtitle": "即時の実用性と長期的な資産価値向上を兼ね備えた物件で、ROI を最大化しましょう。",
    "value_live_1_str": "プレミアム・コネクティビティ：",
    "value_live_1_desc": "主要な交通ルートへの直接アクセスが可能な戦略的立地により、物流効率を確保。",
    "value_live_2_str": "安全な所有権：",
    "value_live_2_desc": "フル Chanote 権利証（Nor Sor 4 Jor）により、絶対的な法的確実性と融資の容易さを保証。",
    "value_live_3_str": "即建設可能な地形：",
    "value_live_3_desc": "自然に平坦な地盤のため、高額な土盛りや複雑な整地の必要がありません。",
    "value_inv_1_str": "資本増加：",
    "value_inv_1_desc": "インフラ整備と観光需要の拡大に支えられた高資産価値上昇ゾーンに位置。",
    "value_inv_2_str": "運用の多用途性：",
    "value_inv_2_desc": "豪華ヴィラ、プライベートエステート、現代的な倉庫など、幅広い用途に適しています。",
    "value_inv_3_str": "オーナー直接掲載：",
    "value_inv_3_desc": "透明性の高い価格設定とオーナーとの直接対話により、スムーズな取得を実現。",
    "feat_pool_title": "広大な区画",
    "feat_pool_desc": "大規模開発に無限のデザイン柔軟性を提供する、十分な 6 ライの敷地面積。",
    "feat_gym_title": "コンクリート道路アクセス",
    "feat_gym_desc": "公共のコンクリート道路に面しており、建設や将来の運営のための物流がスムーズです。",
    "feat_walk_title": "高価値な環境",
    "feat_walk_desc": "静かながら発展しつつあるエリアに位置し、プライバシーと都市の利เนียンスを両立。",
    "feat_peace_title": "インフラ供給",
    "feat_peace_desc": "電気と水の幹線にすぐにアクセスでき、開発までのリードタイムを大幅に短縮。",
    "feat_park_title": "測量済み境界線",
    "feat_park_desc": "最新の測量により正確な物件境界線を確認済みで、境界トラブルのリスクがありません。",
    "feat_sec_title": "低い敷地準備コスト",
    "feat_sec_desc": "最小限の抜根・整地で済み、すぐに基礎工事を開始できる状態で提供されます。",
    "loc_condo_name": "ホアヒン戦略的土地",
    "loc_condo_addr": "ホアヒン、プラチュアップキーリーカン 77110",
    "loc_condo_desc": "沿岸の豪華さと商業的実用性を結ぶ、開発のホットスポットに最適に位置。",
    "loc_card1_title": "ホアヒン・ビーチサイド",
    "loc_card1_desc": "観光の主要な原動力であり、ホスピタリティ・プロジェクトへの安定した需要を提供。",
    "loc_card1_dist": "車で約 15 分",
    "loc_card2_title": "商圏中心部",
    "loc_card2_desc": "都市施設、マーケット、行政センターに近接した好立地。",
    "loc_card2_dist": "車で約 12 分",
    "loc_card3_title": "レクリエーション＆レジャー",
    "loc_card3_desc": "世界クラスのゴルフコースや家族向けアトラクションに囲まれています。",
    "loc_card3_dist": "車で約 5 分",
    "loc_card4_title": "ライフスタイル小売",
    "loc_card4_desc": "プレミアムなショッピングモールや国際的なレストランへ簡単にアクセス。",
    "loc_card4_dist": "車で約 15 分",
    "loc_card5_title": "交通アクセス",
    "loc_card5_desc": "ホアヒン空港や地域の主要な交通回廊に至近。",
    "loc_card5_dist": "車で約 25 分",
    "loc_card6_title": "家族向けエンターテインメント",
    "loc_card6_desc": "アジア有数のウォータージャングルやアウトドア活動の拠点。",
    "loc_card6_dist": "車で約 20 分",
    "loc_card7_title": "優れた医療施設",
    "loc_card7_desc": "トップクラスの国際的な医療機関からわずか数分の距離。",
    "loc_card7_dist": "車で約 20 分",
    "loc_card8_title": "主要ジャンクション/小売",
    "loc_card8_desc": "バンコクと結ぶ主要幹線道路沿いの戦略的なランドマーク。",
    "loc_card8_dist": "車で約 25 分",
    "loc_main_subtitle": "ホアヒンの拡大するインフラと観光需要を活用するための戦略的ポジション。",
    "gal_flt_bld": "土地資産",
    "gal_flt_liv": "マッピング",
    "gal_flt_fac": "接続性",
    "video_section_title": "空撮サイト・インサイト",
    "video_section_subtitle": "区画の規模と戦略的周辺環境を上空から包括的に確認できます。",
    "potential_title": "高収益開発の可能性",
    "potential_subtitle": "柔軟性を重視して設計されたこの土地は、多様な高価値開発モデルをサポートします。",
    "pot_resort_title": "ホスピタリティ＆ウェルネス",
    "pot_resort_desc": "静かな環境での隠れ家的なブティックリゾート、ウェルネス施設、高齢者ケアセンター、またはリタイアメントヴィレッジの設計に最適です。",
    "pot_housing_title": "レジデンシャル・コミュニティ",
    "pot_housing_desc": "安全な住宅団地、豪華ヴィラ、または第二の拠点としてのプライベートクラスターに最適。",
    "pot_warehouse_title": "物流＆ストレージ",
    "pot_warehouse_desc": "道路アクセスを活かしたスマートな保管ソリューションや配送センターに。",
    "pot_factory_title": "商業・工業",
    "pot_factory_desc": "軽工業の製造や最新技術に対応した産業施設など、ニーズに合わせて活用可能。",
    "contact_col_loc_desc": "ホアヒン 6 ライ戦略的土地<br>ホアヒン、プラチュアップキーリーカン"
  },
  "ko": {
    "hero_subtitle": "후아힌의 고성장 지역 내 6라이 규모 전략적 투자 기회.",
    "featured_title": "프라임 개발 토지",
    "featured_subtitle": "고급 리조트, 주거 단지 또는 산업 시설에 적합한 Chanote 문서 포함 6라이 토지.",
    "about_title": "전략적 투자 자산",
    "about_desc": "급변하는 후아힌 통로에 위치한 이 방대한 6라이(9,600sqm) 토지는 최고의 개발 기회를 제공합니다. 평탄한 지형과 공공 콘크리트 도로에 즉각적으로 접근할 수 있는 이 부지는 다양한 고부가가치 프로젝트에 최적화되어 있습니다. 평화로운 주변 환경에는 개인 주택, 풀빌라 단지, 파인애플 농장, 주택 단지 등이 있습니다. 소유주 직거래로 중개 수수료 없이 간소화된 거래를 진행하세요.",
    "stat_room_title": "총 면적",
    "stat_room_desc": "6 라이 (9,600 sq.m.)",
    "stat_scale_title": "법적 상태",
    "stat_scale_desc": "Chanote (레드 가루다)",
    "stat_loc_title": "용도 지역",
    "stat_loc_desc": "다목적 개발 가능",
    "stat_width_title": "도로 접면",
    "stat_width_desc": "넓은 공도 접근성",
    "price_amount": "20,000,000 바트",
    "value_main_title": "투자 하이라이트",
    "value_main_subtitle": "즉각적인 활용도와 장기적인 자산 상승을 모두 갖춘 부동산으로 ROI를 극대화하세요.",
    "value_live_1_str": "프리미엄 연결성:",
    "value_live_1_desc": "주요 교통망과 직접 연결된 전략적 위치로 물류 효율성 확보.",
    "value_live_2_str": "안전한 소유권:",
    "value_live_2_desc": "완벽한 Chanote 권리증(Nor Sor 4 Jor)으로 법적 확실성과 대출 용이성 보장.",
    "value_live_3_str": "즉시 건설 가능한 지형:",
    "value_live_3_desc": "자연적으로 평탄한 지반으로 값비싼 성토나 복잡한 평탄화 작업 불필요.",
    "value_inv_1_str": "자본 성장:",
    "value_inv_1_desc": "현지 인프라 확충과 관광 수요 증가로 인한 고부가가치 상승 지역에 위치.",
    "value_inv_2_str": "운영의 다양성:",
    "value_inv_2_desc": "고급 빌라, 프라이빗 대저택, 현대식 창고 등 광범위한 용도에 적합.",
    "value_inv_3_str": "소유주 직거래 매물:",
    "value_inv_3_desc": "투명한 가격 책정과 소유주와의 직접 소통으로 원활한 인수 지원.",
    "feat_pool_title": "광활한 부지",
    "feat_pool_desc": "대규모 개발을 위해 무한한 설계 유유성을 제공하는 6라이의 대규모 면적.",
    "feat_gym_title": "콘크리트 도로 접근성",
    "feat_gym_desc": "공공 콘크리트 도로와 접해 있어 건설 및 향후 운영을 위한 물류 이동이 원활합니다.",
    "feat_walk_title": "고부가가치 환경",
    "feat_walk_desc": "조용하면서도 개발 중인 지역에 위치하여 프라이버시와 도시의 편리함 공존.",
    "feat_peace_title": "유틸리티 통합",
    "feat_peace_desc": "전기 및 수도 간선 연결이 용이하여 개발 리드타임을 대폭 단축.",
    "feat_park_title": "측량 완료된 경계",
    "feat_park_desc": "최신 측량을 통해 정확한 부동산 경계선 확인, 경계 분쟁 우려 없음.",
    "feat_sec_title": "낮은 부지 조성 비용",
    "feat_sec_desc": "최소한의 부지 정리로 즉시 기초 공사 시작 가능.",
    "loc_condo_name": "후아힌 전략적 토지",
    "loc_condo_addr": "후า힌, 프라추압키리칸 77110",
    "loc_condo_desc": "해안의 럭셔리와 상업적 이점을 잇는 개발 핫스팟에 최적의 위치.",
    "loc_card1_title": "후า힌 해변가",
    "loc_card1_desc": "숙박 프로젝트에 대한 안정적인 수요를 제공하는 주요 관광 허브.",
    "loc_card1_dist": "차로 약 15분",
    "loc_card2_title": "상업 중심지",
    "loc_card2_desc": "시내 편의시설, 시장, 관공서와 인접한 편리한 위치.",
    "loc_card2_dist": "차로 약 12분",
    "loc_card3_title": "휴양 및 레저",
    "loc_card3_desc": "세계적인 수준의 골프장과 가족 지향적 명소들로 둘러싸임.",
    "loc_card3_dist": "차로 약 5분",
    "loc_card4_title": "라이프스타일 쇼핑",
    "loc_card4_desc": "프리미엄 쇼핑몰과 다양한 국제 식당가 이용 용이.",
    "loc_card4_dist": "차로 약 15분",
    "loc_card5_title": "교통 이용",
    "loc_card5_desc": "후า힌 공항 및 주요 지역 이동 통로와 인접.",
    "loc_card5_dist": "차로 약 25분",
    "loc_card6_title": "가족 엔터테인먼트",
    "loc_card6_desc": "아시아 최고의 워터 정글과 야외 활동의 중심지.",
    "loc_card6_dist": "차로 약 20분",
    "loc_card7_title": "최고급 의료 서비스",
    "loc_card7_desc": "수준 높은 국제 의료 시설까지 단 몇 분 거리.",
    "loc_card7_dist": "차로 약 20분",
    "loc_card8_title": "주요 분기점/쇼핑",
    "loc_card8_desc": "방콕과 연결되는 주요 도로상의 전략적 랜드마크.",
    "loc_card8_dist": "차로 약 25분",
    "loc_main_subtitle": "후า힌의 확장되는 인프라와 관광 시장을 활용하기 위한 전략적 위치.",
    "gal_flt_bld": "토지 자산",
    "gal_flt_liv": "모형 배치",
    "gal_flt_fac": "연결성",
    "video_section_title": "항공 사이트 인사이트",
    "video_section_subtitle": "드론 시점으로 본 부지의 규모와 전략적 주변 환경 정보.",
    "potential_title": "고수익 개발 잠재력",
    "potential_subtitle": "유연성을 고려해 설계된 이 토지는 다양한 고부가가치 개발 모델을 지원합니다.",
    "pot_resort_title": "환대 및 웰니스",
    "pot_resort_desc": "평화로운 환경의 프라이빗 부티크 리조트, 웰니스 휴양 시설, 노인 요양 센터 또는 은퇴 마을을 설계해 보세요.",
    "pot_housing_title": "주거 커뮤니티",
    "pot_housing_desc": "보안이 강화된 주거 단지, 고급 빌라 또는 독채 주거군에 이상적.",
    "pot_warehouse_title": "물류 및 창고",
    "pot_warehouse_desc": "도로 접근성을 활용한 스마트 보관 솔루션 또는 유통 센터 구축.",
    "pot_factory_title": "상업용 산업",
    "pot_factory_desc": "경공업 제조 또는 기술 기반 산업 시설에 최적화 가능.",
    "contact_col_loc_desc": "후า힌 6라이 전략 토지<br>후า힌, 프라추압키리칸"
  },
  "lo": {
    "hero_subtitle": "ໂອກາດການລົງທຶນທາງຍຸດທະສາດໃນດິນ 6 ໄຣ່ ໃນໂຊນທີ່ມີການເຕີບໂຕສູງຂອງຫົວຫີນ.",
    "featured_title": "ດິນເພື່ອການພັດທະນາທຳເລທອງ",
    "featured_subtitle": "ເນື້ອທີ່ 6 ໄຣ່ ພ້ອມໂສນົດຄຣຸດແດງ, ເໝາະສົມທີ່ສຸດສຳລັບຣີສອດຫຼູ, ໝູ່ບ້ານ ຫຼື ໂກດັງສິນຄ້າ.",
    "about_title": "ສິນຊັບເພື່ອການລົງທຶນທາງຍຸດທະສາດ",
    "about_desc": "ດິນເນື້ອທີ່ກວ້າງ 6 ໄຣ່ (9,600 ຕຣ.ມ.) ນີ້ແມ່ນໂອກາດທອງສຳລັບການພັດທະນາໃນເຂດທີ່ມີການຂະຫຍายຕົວຂອງຫົວຫີນ. ດ້ວຍລັກສະນະດິນທີ່ພຽງດີ ແລະ ເຂົ້າເຖິງທາງເບຕົງໄດ້ທັນທີ, ພື້ນທີ່ນີ້ໄດ້ຖືກປັບປຸງໃຫ້ເໝາະສຳລັບໂຄງການທີ່ມີມູນຄ່າສູງ. ແວດລ້ອມໄປດ້ວຍເພື່ອນບ້ານທີ່ງຽບສະຫງົບ ທັງບ້ານດ່ຽວ, ໝູ່ບ້ານພູລວິນລ່າ, ສວນນັດ ແລະ ໝູ່ບ້ານຈັດສັນ. ຊື້ຂາຍໂດຍກົງຈາກເຈົ້າຂອງເພື່ອຄວາມສະດວກ ແລະ ປະຢັດຄ່ານາຍໜ້າ.",
    "stat_room_title": "ເນື້ອທີ່ທັງໝົດ",
    "stat_room_desc": "6 ໄຣ່ (9,600 ຕຣ.ມ.)",
    "stat_scale_title": "ສະຖານະທາງກົດໝາຍ",
    "stat_scale_desc": "ໂສນົດ (ຄຣຸດແດງ ນ.ສ. 4 ຈ.)",
    "stat_loc_title": "ຜັງເມືອງ",
    "stat_loc_desc": "ຮອງຮັບການພັດທະນາທີ່ຫຼາກຫຼາຍ",
    "stat_width_title": "ໜ້າກວ້າງທາງ",
    "stat_width_desc": "ຕິດທາງສາທາລະນະກວ້າງ",
    "price_amount": "20,000,000 ບາດ",
    "value_main_title": "ຈຸດເດັ່ນຂອງການລົງທຶນ",
    "value_main_subtitle": "ເພີ່ມຜົນຕອບແທນສູງສຸດດ້ວຍອະສັງຫາລິມະຊັບທີ່ພ້ອมໃຊ້ງານທັນທີ ແລະ ມີມູນຄ່າເພີ່ມໃນໄລຍະຍາວ.",
    "value_live_1_str": "ການເຊື່ອມຕໍ່ທີ່ຍອດຢ້ຽມ:",
    "value_live_1_desc": "ຕັ້ງຢູ່ໃນທຳເລຍຸດທະສາດທີ່ເຊື່ອມຕໍ່ກັບເສັ້ນທາງຄົມມະນາຄົມຫຼັກ ໝັ້ນໃຈໃນປະສິດທິຜົນດ້ານการຂົນສົ່ງ.",
    "value_live_2_str": "ກຳມະສິດທີ່ປອດໄພ:",
    "value_live_2_desc": "ໂສນົດທີ່ດິນຄຣຸດແດງທີ່ຊັດເຈນ ໝັ້ນໃຈໃນຄວາມຖືກຕ້ອງທາງກົດໝາຍ ແລະ ງ່າຍຕໍ່ການຂໍສິນເຊື່ອ.",
    "value_live_3_str": "ພື້ນທີ່ພ້ອມກໍ່ສ້າງ:",
    "value_live_3_desc": "ດິນທີ່ພຽງຕາມທຳມະຊາດຊ່ວยປະຢັດຄ່າໃຊ້ຈ່າຍໃນການປັບພື້ນທີ່ທີ່ຍາກລຳບາກ.",
    "value_inv_1_str": "ການເຕີບໂຕຂອງເງິນທຶນ:",
    "value_inv_1_desc": "ຢູ່ໃນໂຊນທີ່ມີມູນຄ່າເພີ່ມສູງ ດ້ວຍແຮງໜູນຈາກໂຄງສ້າງພື້ນຖານ ແລະ ການທ່ອງທ່ຽວ.",
    "value_inv_2_str": "ການໃຊ້ງານທີ່ຫຼາກຫຼາຍ:",
    "value_inv_2_desc": "ເໝາະສຳລັບການໃຊ້ງານທີ່ກວ້າງຂວາງ ເຊັ່ນ ວິນລ່າຫຼູ, ໝູ່ບ້ານ ຫຼື ຄັງສິນຄ້າ.",
    "value_inv_3_str": "ຕິດຕໍ່ເຈົ້າຂອງໂດຍກົງ:",
    "value_inv_3_desc": "ລາຄາໂປ່ງໃສ ແລະ ການສື່ສານໂດຍກົງກັບເຈົ້າຂອງ ເພື່ອຂັ້ນຕອນການຊື້ຂายທີ່ລາບລື່ນ.",
    "feat_pool_title": "ດິນຕອນໃຫຍ່",
    "feat_pool_desc": "ພື້ນທີ່ 6 ໄຣ່ທີ່ກວ້າງຂວາງ ໃຫ້ຄວາມຢືດຢຸ່ນບໍ່ຈຳກັດໃນການອອກແບບສຳລັບໂຄງການໃຫຍ່.",
    "feat_gym_title": "ຕິດທາງເບຕົງ",
    "feat_gym_desc": "ຕິດທາງສາທາລະນະເບຕົງ ໃຫ້ຄວາມສະດວກໃນການຂົນສົ່ງສຳລັບວຽກກໍ່ສ້າງ ແລະ ການດຳເນີນງານ.",
    "feat_walk_title": "ສະພາບແວດລ້ອມມູນຄ່າສູง",
    "feat_walk_desc": "ຢູ່ໃນພື້ນທີ່ທີ່ງຽບສະຫງົບແຕ່ກຳລັງພັດທະນາ ໃຫ້ຄວາມລົງຕົວລະຫວ່າງຄວາມເປັນສ່ວນຕົວ ແລະ ຄວາມສະດວກສະບາຍ.",
    "feat_peace_title": "ລະບົບພື້ນຖານພ້ອມ",
    "feat_peace_desc": "ລະບົບໄຟຟ້າ ແລະ ນ້ຳປະປາເຂົ້າເຖິງພື້ນທີ່ ຊ່ວยຫຼຸດໄລຍະເວລາໃນການຂໍໃຊ້ບໍລິການ.",
    "feat_park_title": "ແນວເຂດຊັດເຈນ",
    "feat_park_desc": "ຜ່ານການວັດແທກຫຼ້າສຸດ ຢືນຢັນແນວເຂດທີ່ຖືກຕ້ອງ ໝັ້ນໃຈບໍ່ມີບັນຫາການບຸກລຸກ.",
    "feat_sec_title": "ຄ່າກະກຽມພື້ນທີ່ຕ່ຳ",
    "feat_sec_desc": "ດິນພ້ອມໃຊ້ງານທັນທີ ບໍ່ຕ້ອງມີວຽກປັບສະພາບດິນທີ່ຍາກ ສາມາດເລີ່ມວຽກພື້ນຖານໄດ້ເລີຍ.",
    "loc_condo_name": "ດິນຍຸດທະສາດ ຫົວຫີນ",
    "loc_condo_addr": "ຫົວຫີນ, ປະຈວບຄີຣີຂັນ 77110",
    "loc_condo_desc": "ຕັ້ງຢູ່ໃນທຳເລສັກກະຍະພາບຂອງການພັດທະນາ ເຊື່ອມຕໍ່ຄວາມຫຼູຫຼາ ແລະ ການໃຊ້ງານໄດ້ຢ່າງລົງຕົວ.",
    "loc_card1_title": "ຊາຍຫາດຫົວຫີນ",
    "loc_card1_desc": "ປັດໄຈຫຼັກຂັບເຄື່ອນການທ່ອງທ່ຽວທີ່ສ້າງຄວາມຕ້ອງການຢ່າງຕໍ່ເນື່ອງ.",
    "loc_card1_dist": "ຂັບລົດ ~15 ນາທີ",
    "loc_card2_title": "ສູນກາງທຸລະກິດ",
    "loc_card2_desc": "ຕັ້ງຢູ່ໃກ້ສິ່ງອຳນວຍความສະດວກໃນເມືອງ, ຕະຫຼາດ ແລະ ສູນລັດຖະການ.",
    "loc_card2_dist": "ຂັບລົດ ~12 ນາທີ",
    "loc_card3_title": "ການພັກຜ່ອນຢ່ອນໃຈ",
    "loc_card3_desc": "ລ້ອມຮອບດ້ວຍສະໜາມກອຟລະດັບໂລກ ແລະ ສະຖານທີ່ທ່ອງທ່ຽວຄອບຄົວ.",
    "loc_card3_dist": "ຂับລົດ ~20 ນາທີ",
    "loc_card4_title": "ຫ້າງສັບພະສິນຄ້າ",
    "loc_card4_desc": "ເຂົ້າເຖິງແຫຼ່ງຊ້ອບປິ້ງລະດັບພຣີມຽມ ແລະ ຮ້านອາຫານນານາຊາດ.",
    "loc_card4_dist": "ຂັບລົດ ~15 ນາທີ",
    "loc_card5_title": "ການຄົມມะนาຄົມ",
    "loc_card5_desc": "ໃກ້ສະໜາມບິນຫົວຫີນ ແລະ ເສັ້ນທາງຄົມມะนาຄົມລະດັບພາກພື້ນ.",
    "loc_card5_dist": "ຂັບລົດ ~25 ນາທີ",
    "loc_card6_title": "ຄວາມບັນເທີງຄອບຄົວ",
    "loc_card6_desc": "ແຫຼ່ງລວມສວນນ້ຳຊັ້ນນຳ ແລະ ກິດຈະກຳກາງແຈ້ງທີ່ຍອດນິຍົມ.",
    "loc_card6_dist": "ຂັບລົດ ~20 ນາທີ",
    "loc_card7_title": "ການແພດຊັ້ນນຳ",
    "loc_card7_desc": "ໃກ້ໂຮงໝໍລະດັບນານาຊາດຊັ້ນນຳໃນພື້ນທີ່.",
    "loc_card7_dist": "ຂັບລົດ ~20 ນາທີ",
    "loc_card8_title": "ຈຸດພັກລົດຫຼັກ",
    "loc_card8_desc": "ຈຸດແລນມາກສຳຄັນເທິງເສັ້ນທາງຫຼັກທີ່ເຊື່ອມຕໍ່ຫາບາງກອກ.",
    "loc_card8_dist": "ຂັບລົດ ~25 ນາທີ",
    "loc_main_subtitle": "ວາງຕຳແໜ່ງຢ່າງເໝາະສົມເພື່ອຮັບຜົນປະໂຫຍດຈາກການຂະຫຍາຍຕົວຂອງຫົວຫີນ.",
    "gal_flt_bld": "ຊັບສິນດິນ",
    "gal_flt_liv": "ແຜນທີ່",
    "gal_flt_fac": "ການເຊື່ອມຕໍ່",
    "video_section_title": "ຂໍ້ມູນແບບມຸມສູງ",
    "video_section_subtitle": "ສຳຜັດສັກກະຍະພາບ ແລະ ຂະໜາດຂອງດິນຜ່ານມຸມມອງໂດຣນ.",
    "potential_title": "ສັກກະຍະພາບການພັດທະນາທີ່ໃຫ້ຜົນຕອບແທນສູງ",
    "potential_subtitle": "ຖືກອອກແບບມາເພື່ອຄວາມຢືດຢຸ່ນ, ດິນຕອນນີ້ຮອງຮັບການພັດທະນາຫຼາຍຮູບແບບ.",
    "pot_resort_title": "ການບໍລິການ ແລະ ສຸຂະພາບ",
    "pot_resort_desc": "ອອກແບບບູທີຄຣີສອດ, ສະຖານທີ່ພັກຜ່ອນເພື່ອສຸຂະພາບ, ສູນດູແລຜູ້ສູງອາຍຸ ຫຼື ໝູ່ບ້ານກະສຽນອາຍຸໃນບັນຍາກາດທີ່ເງຽບສະຫງົບ.",
    "pot_housing_title": "ຊຸມຊົນທີ່ຢູ່ອາໄສ",
    "pot_housing_desc": "ເໝາະສຳລັບໂຄງການບ້ານຈັດສັນ, ວິນລ່າຫຼູ ຫຼື ບ້ານພັກຕາກອາກາດ.",
    "pot_warehouse_title": "ໂລຈິສຕິກ ແລະ ສາງສິນຄ້າ",
    "pot_warehouse_desc": "ໃຊ້ປະໂຫຍດຈາກການເຂົ້າເຖິງທາງເພື່ອສ້າງສາງສິນຄ້າທີ່ທັນສະໄໝ.",
    "pot_factory_title": "ອຸດສາຫະກຳ",
    "pot_factory_desc": "ອອກແບບມາເປັນພິເສດສຳລັບການຜະລິດອຸດສາຫະກຳເບົາ ຫຼື ສິ່ງອຳນວຍຄວາມສະດວກດ້ານເຕັກໂນໂລຢີ.",
    "contact_col_loc_desc": "ດິນຍຸດທະສາດ 6 ໄຣ່<br>ຫົວຫີນ, ປະຈວບຄີຣີຂັນ"
  }
};

var propertyBasePath = "";

var propertyCategory = "Land";

var propertyGallery = [
    { src: "land/dji_fly_20260415_095936_0016_1776239662408_photo_beautify.webp", category: "land" },
    { src: "land/f1.webp", category: "land" },
    { src: "land/f2.webp", category: "land" },
    { src: "land/f3.webp", category: "land" },
    { src: "land/f4.webp", category: "land" },
    { src: "land/f5.webp", category: "land" },
    { src: "land/f6.webp", category: "land" },
    { src: "map/map1.webp", category: "map" },
    { src: "nearby/nearby_1.webp", category: "nearby" },
    { src: "nearby/nearby_2.webp", category: "nearby" },
    { src: "nearby/nearby_3.webp", category: "nearby" },
    { src: "nearby/nearby_4.webp", category: "nearby" },
    { src: "nearby/nearby_5.webp", category: "nearby" }
];
