const propertyContent = {
  "en": {
    "featured_title": "Featured Property: dcondo Ping",
    "featured_subtitle": "The power of modern living. Blending the growth of Chiang Mai with the charm of the Ping River.",
    "about_title": "Inspired by the Ping River",
    "about_desc": "Developed by renowned developer Sansiri in 2018, dcondo Ping consists of 687 units across 4 eight-story buildings. Located in the peaceful Fah Ham neighborhood, it offers a tranquil urban lifestyle surrounded by nature. The large communal areas are inspired by the charm of the Ping River. Enjoy unparalleled convenience with an exclusive private walkway providing direct access to Central Festival Chiang Mai in just a few minutes, while the international airport is only 7km away.",
    "stat_room_desc": "Studio (30), 1 Bed (37), 2 Bed (60) sq.m.",
    "stat_scale_desc": "4 Buildings, 8 Floors, 687 Units",
    "stat_loc_desc": "Private Walkway to Central Festival",
    "price_amount": "฿2.3M THB",
    "value_main_title": "Why Choose dcondo Ping?",
    "value_main_subtitle": "Whether you are looking for your perfect home or a high-yield asset, this property delivers.",
    "value_live_1_str": "Serene Retreat:",
    "value_live_1_desc": "Escape the city noise in this peaceful, resort-style environment.",
    "value_live_2_str": "Daily Convenience:",
    "value_live_2_desc": "A private, direct walkway to Central Festival mall for all your shopping and dining needs.",
    "value_live_3_str": "Premium Facilities:",
    "value_live_3_desc": "Enjoy the massive pool, modern gym, and beautifully landscaped gardens.",
    "value_inv_1_str": "High Rental Yield:",
    "value_inv_1_desc": "Generating strong yields with proven rental rates starting from <strong>฿15,000/month</strong> (7.5% Gross Yield Target).",
    "value_inv_2_str": "Unbeatable Demand:",
    "value_inv_2_desc": "Proximity to Central Festival ensures constant high demand from both locals and expats.",
    "value_inv_3_str": "Capital Appreciation:",
    "value_inv_3_desc": "Located in Chiang Mai's most rapidly developing premium residential node.",
    "feat_pool_title": "Massive Resort Pool",
    "feat_pool_desc": "Relax in the expansive, sparkling communal swimming pool, highly rated by residents for cleanliness and size.",
    "feat_gym_title": "Fitness Center",
    "feat_gym_desc": "Fully equipped modern gym overlooking the lush resort-style gardens, perfect for your wellness routine.",
    "feat_walk_title": "Private Walkway",
    "feat_walk_desc": "Exclusive private walking path connecting the condominium directly to Central Festival Chiang Mai.",
    "feat_peace_title": "Peaceful Environment",
    "feat_peace_desc": "Set in the quiet Fah Ham area, offering a serene escape while remaining just a short 10-minute drive to the vibrant Old City.",
    "feat_park_title": "Parking Space",
    "feat_park_desc": "Ample parking available for residents and their guests.",
    "feat_sec_title": "24/7 Security",
    "feat_sec_desc": "Complete peace of mind with round-the-clock security and CCTV.",
    "loc_condo_name": "dcondo Ping by Sansiri",
    "loc_condo_addr": "Fa Ham, Mueang Chiang Mai District, Chiang Mai 50000",
    "loc_condo_desc": "Located exceptionally close to Central Festival with a private walkway for residents, offering serene living along the Ping River.",
    "loc_card1_title": "Central Festival Chiang Mai",
    "loc_card1_desc": "Top shopping, dining, and entertainment destination.",
    "loc_card1_dist": "200m (Private Walkway)",
    "loc_card2_title": "Nimmanhaemin Road",
    "loc_card2_desc": "Trendy cafes, boutiques, and nightlife.",
    "loc_card2_dist": "~10 Mins Drive",
    "loc_card3_title": "Chiang Mai Old City",
    "loc_card3_desc": "Historic temples, Sunday night market, cultural hub.",
    "loc_card3_dist": "~10 Mins Drive",
    "loc_card4_title": "Maya Lifestyle Shopping Center",
    "loc_card4_desc": "Premium lifestyle mall with cinema, dining, and rooftop bars.",
    "loc_card4_dist": "~10 Mins Drive",
    "loc_card5_title": "Chiang Mai University (CMU)",
    "loc_card5_desc": "Top university in Northern Thailand with lush green campus.",
    "loc_card5_dist": "~12 Mins Drive",
    "loc_card6_title": "Tha Phae Gate",
    "loc_card6_desc": "Iconic historic landmark and entrance to the Old City.",
    "loc_card6_dist": "~10 Mins Drive",
    "loc_card7_title": "Bangkok Hospital Chiang Mai",
    "loc_card7_desc": "Premium healthcare and medical services.",
    "loc_card7_dist": "1.5 km",
    "loc_card8_title": "Chiang Mai International Airport",
    "loc_card8_desc": "Domestic and international flights.",
    "loc_card8_dist": "7.5 km",
    "contact_col_loc_desc": "dcondo Ping by Sansiri<br>Fa Ham, Mueang Chiang Mai 50000"
  },
  "th": {
    "featured_title": "ทรัพย์สินแนะนำ: ดีคอนโด ปิง (dcondo Ping)",
    "featured_subtitle": "พลังแห่งการใช้ชีวิตสไตล์โมเดิร์น ผสมผสานความเจริญของเชียงใหม่เข้ากับมนต์เสน่ห์ของแม่น้ำปิง",
    "about_title": "แรงบันดาลใจจากแม่น้ำปิง",
    "about_desc": "พัฒนาโดยผู้พัฒนาชื่อดังอย่าง แสนสิริ ในปี 2018 ดีคอนโด ปิง ประกอบด้วย 687 ยูนิตใน 4 อาคาร สูง 8 ชั้น ตั้งอยู่ในย่านฟ้าฮ่ามที่เงียบสงบ มอบไลฟ์สไตล์คนเมืองที่เงียบสงบท่ามกลางธรรมชาติ พื้นที่ส่วนกลางขนาดใหญ่ได้รับแรงบันดาลใจจากมนต์เสน่ห์ของแม่น้ำปิง เพลิดเพลินกับความสะดวกสบายที่เหนือชั้นด้วยทางเดินเท้าส่วนตัวสุดพิเศษที่เชื่อมตรงไปยังเซ็นทรัลเฟสติวัลเชียงใหม่ในเวลาเพียงไม่กี่นาที ในขณะที่สนามบินนานาชาติอยู่ห่างออกไปเพียง 7 กม.",
    "stat_room_desc": "สตูดิโอ (30), 1 ห้องนอน (37), 2 ห้องนอน (60) ตร.ม.",
    "stat_scale_desc": "4 อาคาร, 8 ชั้น, 687 ยูนิต",
    "stat_loc_desc": "ทางเดินส่วนตัวไปเซ็นทรัลเฟสติวัล",
    "price_amount": "฿2.3 ล้านบาท",
    "value_main_title": "ทำไมต้องเลือก ดีคอนโด ปิง?",
    "value_main_subtitle": "ไม่ว่าคุณจะกำลังมองหาบ้านที่สมบูรณ์แบบหรือสินทรัพย์ที่ให้ผลตอบแทนสูง ที่นี่คือคำตอบที่ใช่",
    "value_live_1_str": "สถานที่พักผ่อนที่เงียบสงบ:",
    "value_live_1_desc": "หลีกหนีความวุ่นวายของเมืองในสภาพแวดล้อมที่เงียบสงบสไตล์รีสอร์ท",
    "value_live_2_str": "สะดวกสบายทุกวัน:",
    "value_live_2_desc": "ทางเดินเท้าส่วนตัวเชื่อมตรงไปยังห้างเซ็นทรัลเฟสติวัลสำหรับทุกความต้องการในการช้อปปิ้งและรับประทานอาหาร",
    "value_live_3_str": "สิ่งอำนวยความสะดวกระดับพรีเมียม:",
    "value_live_3_desc": "เพลิดเพลินกับสระว่ายน้ำขนาดใหญ่ ฟิตเนสที่ทันสมัย และสวนที่ตกแต่งอย่างสวยงาม",
    "value_inv_1_str": "ผลตอบแทนค่าเช่าสูง:",
    "value_inv_1_desc": "สร้างผลตอบแทนที่แข็งแกร่งด้วยอัตราค่าเช่าที่พิสูจน์แล้วเริ่มต้นที่ <strong>฿15,000/เดือน</strong> (เป้าหมายผลตอบแทนขั้นต้น 7.5%)",
    "value_inv_2_str": "ความต้องการที่ไม่มีใครเทียบได้:",
    "value_inv_2_desc": "ความใกล้ชิดกับเซ็นทรัลเฟสติวัลทำให้มีความต้องการสูงอย่างต่อเนื่องจากทั้งคนในพื้นที่และชาวต่างชาติ",
    "value_inv_3_str": "มูลค่าเพิ่มของเงินทุน:",
    "value_inv_3_desc": "ตั้งอยู่ในย่านที่พักอาศัยระดับพรีเมียมที่พัฒนาเร็วที่สุดในเชียงใหม่",
    "feat_pool_title": "สระว่ายน้ำสไตล์รีสอร์ทขนาดใหญ่",
    "feat_pool_desc": "ผ่อนคลายในสระว่ายน้ำส่วนกลางที่กว้างขวางและส่องประกาย ซึ่งได้รับการจัดอันดับสูงจากผู้อยู่อาศัยเรื่องความสะอาดและขนาด",
    "feat_gym_title": "ศูนย์ฟิตเนส",
    "feat_gym_desc": "ฟิตเนสที่ตกแต่งอย่างครบครันและทันสมัย สามารถมองเห็นสวนสไตล์รีสอร์ทอันเขียวชอุ่ม เหมาะสำหรับกิจวัตรเพื่อสุขภาพของคุณ",
    "feat_walk_title": "ทางเดินส่วนตัว",
    "feat_walk_desc": "เส้นทางเดินส่วนตัวสุดพิเศษที่เชื่อมต่อคอนโดมิเนียมเข้ากับเซ็นทรัลเฟสติวัลเชียงใหม่โดยตรง",
    "feat_peace_title": "สภาพแวดล้อมที่เงียบสงบ",
    "feat_peace_desc": "ตั้งอยู่ในทำเลที่เงียบสงบย่านฟ้าฮ่าม มอบการหลีกหนีที่เงียบสงบ ในขณะที่ขับรถเพียง 10 นาทีไปยังย่านเมืองเก่าที่คึกคัก",
    "feat_park_title": "ที่จอดรถ",
    "feat_park_desc": "ที่จอดรถกว้างขวางมีให้บริการสำหรับผู้พักอาศัยและแขกของพวกเขา",
    "feat_sec_title": "การรักษาความปลอดภัย 24/7",
    "feat_sec_desc": "อุ่นใจได้อย่างเต็มที่ด้วยการรักษาความปลอดภัยตลอด 24 ชั่วโมงและกล้องวงจรปิด",
    "loc_condo_name": "ดีคอนโด ปิง บาย แสนสิริ (dcondo Ping by Sansiri)",
    "loc_condo_addr": "ฟ้าฮ่าม อำเภอเมืองเชียงใหม่ เชียงใหม่ 50000",
    "loc_condo_desc": "ตั้งอยู่ใกล้กับเซ็นทรัลเฟสติวัลอย่างโดดเด่นพร้อมทางเดินส่วนตัวสำหรับผู้พักอาศัย มอบวิถีชีวิตที่เงียบสงบเลียบแม่น้ำปิง",
    "loc_card1_title": "เซ็นทรัลเฟสติวัล เชียงใหม่ (Central Festival)",
    "loc_card1_desc": "แหล่งช้อปปิ้ง ร้านอาหาร และความบันเทิงชั้นนำ",
    "loc_card1_dist": "200 เมตร (ทางเดินส่วนตัว)",
    "loc_card2_title": "ถนนนิมมานเหมินท์",
    "loc_card2_desc": "คาเฟ่สุดชิค บูติก และสถานบันเทิงยามค่ำคืน",
    "loc_card2_dist": "ขับรถ ~10 นาที",
    "loc_card3_title": "เมืองเก่าเชียงใหม่",
    "loc_card3_desc": "วัดประวัติศาสตร์ ถนนคนเดินวันอาทิตย์ ศูนย์กลางวัฒนธรรม",
    "loc_card3_dist": "ขับรถ ~10 นาที",
    "loc_card4_title": "ศูนย์การค้า เมญ่า ไลฟ์สไตล์ (MAYA)",
    "loc_card4_desc": "ห้างสรรพสินค้าไลฟ์สไตล์ระดับพรีเมียมพร้อมโรงภาพยนตร์ ร้านอาหาร และรูฟท็อปบาร์",
    "loc_card4_dist": "ขับรถ ~10 นาที",
    "loc_card5_title": "มหาวิทยาลัยเชียงใหม่ (มช.)",
    "loc_card5_desc": "มหาวิทยาลัยชั้นนำในภาคเหนือของประเทศไทยพร้อมวิทยาเขตสีเขียวชอุ่ม",
    "loc_card5_dist": "ขับรถ ~12 นาที",
    "loc_card6_title": "ประตูท่าแพ",
    "loc_card6_desc": "สถานที่สำคัญทางประวัติศาสตร์และทางเข้าสู่เมืองเก่า",
    "loc_card6_dist": "ขับรถ ~10 นาที",
    "loc_card7_title": "โรงพยาบาลกรุงเทพเชียงใหม่",
    "loc_card7_desc": "บริการด้านการดูแลสุขภาพและการแพทย์ระดับพรีเมียม",
    "loc_card7_dist": "1.5 กม.",
    "loc_card8_title": "ท่าอากาศยานนานาชาติเชียงใหม่",
    "loc_card8_desc": "เที่ยวบินภายในประเทศและระหว่างประเทศ",
    "loc_card8_dist": "7.5 กม.",
    "contact_col_loc_desc": "ดีคอนโด ปิง บาย แสนสิริ<br>ตำบลฟ้าฮ่าม อำเภอเมือง จังหวัดเชียงใหม่ 50000"
  },
  "zh": {
    "featured_title": "精选房产：dcondo Ping",
    "featured_subtitle": "现代生活的力量。将清迈的发展与平河的魅力相结合。",
    "about_title": "灵感来自平河",
    "about_desc": "由著名开发商尚思瑞 (Sansiri) 于 2018 年开发，dcondo Ping 包含 4 栋八层建筑，共有 687 个单位。位于宁静的 Fa Ham 街区，在被自然环绕中提供宁静的城市生活方式。大型公共区域以平河的魅力为灵感。只需几分钟，即可通过专属私人走道直接进入清迈 Central Festival 购物中心，享受无与伦比的便利，而国际机场距此仅 7 公里。",
    "stat_room_desc": "单间 (30)、1 卧室 (37)、2 卧室 (60) 平方米",
    "stat_scale_desc": "4 栋建筑，8 层，687 个单位",
    "stat_loc_desc": "直通 Central Festival 购物中心的私人走道",
    "price_amount": "฿230 万泰铢",
    "value_main_title": "为什么选择 dcondo Ping？",
    "value_main_subtitle": "无论您是在寻找完美的家园还是高收益的资产，此房产都能满足您的需求。",
    "value_live_1_str": "宁静的休憩区：",
    "value_live_1_desc": "在这个宁静的度假村式环境中远离城市的喧嚣。",
    "value_live_2_str": "日常便利：",
    "value_live_2_desc": "一条私人且直接的走道通往 Central Festival 购物中心，可满足您所有的购物和餐饮需求。",
    "value_live_3_str": "优质设施：",
    "value_live_3_desc": "享受宽敞的游泳池、现代化的健身房以及风景优美的花园。",
    "value_inv_1_str": "高租金回报率：",
    "value_inv_1_desc": "创造丰厚的回报，经证明的租金起价为 <strong>฿15,000/月</strong>（总收益率目标为 7.5%）。",
    "value_inv_2_str": "无法超越的需求：",
    "value_inv_2_desc": "邻近 Central Festival，确保了当地人和外籍人士的持续高需求。",
    "value_inv_3_str": "资本升值：",
    "value_inv_3_desc": "位于清迈发展最快的优质住宅核心区。",
    "feat_pool_title": "超大度假村游泳池",
    "feat_pool_desc": "在宽广闪亮的公共游泳池中放松身心，这里的清洁度和规模受到居民的好评。",
    "feat_gym_title": "健身中心",
    "feat_gym_desc": "设备齐全的现代健身房可俯瞰郁郁葱葱的度假村式花园，是您日常健康锻炼的理想场所。",
    "feat_walk_title": "私人走道",
    "feat_walk_desc": "独家专属的私人步道直接将公寓连接到清迈 Central Festival。",
    "feat_peace_title": "宁静的环境",
    "feat_peace_desc": "位于安静的 Fa Ham 地区，提供宁静的避风港，同时开车仅需 10 分钟即可到达繁华的古城。",
    "feat_park_title": "停车位",
    "feat_park_desc": "为居民及其客人提供充足的停车位。",
    "feat_sec_title": "24/7 安保系统",
    "feat_sec_desc": "设有全天候的安保和闭路电视，让您彻底安心。",
    "loc_condo_name": "清迈 Sansiri dcondo Ping",
    "loc_condo_addr": "清迈直辖县，Fa Ham 区，50000",
    "loc_condo_desc": "位置极佳，靠近 Central Festival 并设有居民私人走道，沿着平河提供宁静的生活。",
    "loc_card1_title": "清迈 Central Festival",
    "loc_card1_desc": "顶级的购物、餐饮和娱乐目的地。",
    "loc_card1_dist": "200米（私人走道）",
    "loc_card2_title": "宁曼路",
    "loc_card2_desc": "时尚的咖啡馆、精品店和夜生活。",
    "loc_card2_dist": "约 10 分钟车程",
    "loc_card3_title": "清迈古城",
    "loc_card3_desc": "历史悠久的寺庙、周日夜市和文化中心。",
    "loc_card3_dist": "约 10 分钟车程",
    "loc_card4_title": "玛雅生活购物中心",
    "loc_card4_desc": "配有电影院、餐饮和屋顶酒吧的优质生活方式购物中心。",
    "loc_card4_dist": "约 10 分钟车程",
    "loc_card5_title": "清迈大学 (CMU)",
    "loc_card5_desc": "泰国北部的顶尖大学，校园内绿意盎然。",
    "loc_card5_dist": "约 12 分钟车程",
    "loc_card6_title": "塔佩门",
    "loc_card6_desc": "具有标志性的历史地标和古城入口。",
    "loc_card6_dist": "约 10 分钟车程",
    "loc_card7_title": "清迈曼谷医院",
    "loc_card7_desc": "优质医疗保健和医疗服务。",
    "loc_card7_dist": "1.5 公里",
    "loc_card8_title": "清迈国际机场",
    "loc_card8_desc": "提供国内及国际航班服务。",
    "loc_card8_dist": "7.5 公里",
    "contact_col_loc_desc": "Sansiri dcondo Ping<br>清迈 Fa Ham, 50000"
  },
  "lo": {
    "featured_title": "ຊັບສິນແນະນຳ: dcondo Ping",
    "featured_subtitle": "ພະລັງແຫ່ງການໃຊ້ຊີວິດແບບທັນສະໄໝ. ປະສົມປະສານຄວາມຈະເລີນເຕີບໂຕຂອງຊຽງໃໝ່ກັບສະເໜ່ຂອງແມ່ນ້ຳປິງ.",
    "about_title": "ແຮງບັນດານໃຈຈາກແມ່ນ້ຳປິງ",
    "about_desc": "ພັດທະນາໂດຍນັກພັດທະນາຊື່ດັງ Sansiri ໃນປີ 2018, dcondo Ping ປະກອບມີ 687 ຫ້ອງ ໃນ 4 ອາຄານ สูง 8 ຊັ້ນ. ຕັ້ງຢູ່ໃນຍ່ານຟ້າຮ່າມທີ່ງຽບສະຫງົບ, ໃຫ້ຊີວິດໃນເມືອງທີ່ງຽບສະຫງົບທ່າມກາງທຳມະຊາດ. ພື້ນທີ່ສ່ວນກາງຂະໜາດໃຫຍ່ໄດ້ຮັບແຮງບັນດານໃຈຈາກສະເໜ່ຂອງແມ່ນ້ຳປິງ. ເພີດເພີນກັບຄວາມສະດວກສະບາຍທີ່ບໍ່ມີໃຜທຽບໄດ້ດ້ວຍທາງຍ່າງສ່ວນຕົວທີ່ເຊື່ອມຕໍ່ໂດຍກົງຫາເຊັນທຣັນເຟສຕິວໍເຊียงໃໝ່ໃນເວລາພຽງບໍ່ເທົ່າໃດນາທີ, ຂະນະທີ່ສະໜາມບິນນາໆຊາດຢູ່ຫ່າງອອກໄປພຽງ 7 ກິໂລແມັດ.",
    "stat_room_desc": "ສະຕູດິໂອ (30), 1 ຫ້ອງນອນ (37), 2 ຫ້ອງນອນ (60) ຕຣ.ມ.",
    "stat_scale_desc": "4 ອາຄານ, 8 ຊັ້ນ, 687 ຫ້ອງ",
    "stat_loc_desc": "ທາງຍ່າງສ່ວນຕົວຫາເຊັນທຣັນເຟສຕິວໍ",
    "price_amount": "฿2.3 ລ້ານບາດ",
    "value_main_title": "ເປັນຫຍັງຕ້ອງເລືອກ dcondo Ping?",
    "value_main_subtitle": "ບໍ່ວ່າທ່ານຈະກໍາລັງຊອກຫາບ້ານທີ່ສົມບູນແບບຫຼືຊັບສິນທີ່ໃຫ້ຜົນຕອບແທນສູງ, ບ່ອນນີ້ຕອບໂຈດໄດ້.",
    "value_live_1_str": "ສະຖານທີ່ພັກຜ່ອນທີ່ງຽບສະຫງົບ:",
    "value_live_1_desc": "ລົບໜີຈາກສຽງລົບກວນຂອງເມືອງໃນສະພາບແວດລ້ອມແບບຣີສອດທີ່ງຽບສະຫງົບນີ້.",
    "value_live_2_str": "ຄວາມສະດວກສະບາຍປະຈຳວັນ:",
    "value_live_2_desc": "ທາງຍ່າງສ່ວນຕົວແລະໂດຍກົງຫາສູນການຄ້າເຊັນທຣັນເຟສຕິວໍສໍາລັບທຸກຄວາມຕ້ອງການຊື້ເຄື່ອງແລະຮັບປະທານອາຫານຂອງທ່ານ.",
    "value_live_3_str": "ສິ່ງອຳນວຍຄວາມສະດວກລະດັບພຣີມຽມ:",
    "value_live_3_desc": "ເພີດເພີນໄປກັບສະນຸກເກີຂະຫນາດໃຫຍ່, ຫ້ອງອອກກຳລັງກາຍທີ່ທັນສະໄຫມ, ແລະສວນທີ່ສວຍງາມ.",
    "value_inv_1_str": "ຜົນຕອບແທນຄ່າເຊົ່າສູງ:",
    "value_inv_1_desc": "ສ້າງຜົນຕອບແທນທີ່ແຂງແກ່ນດ້ວຍອັດຕາຄ່າເຊົ່າທີ່ພິສູດແລ້ວເລີ່ມຕົ້ນທີ່ <strong>฿15,000/ເດືອນ</strong> (ເປົ້າໝາຍຜົນຕອບແທນລວມ 7.5%).",
    "value_inv_2_str": "ຄວາມຕ້ອງການທີ່ບໍ່ມີໃຜທຽບ:",
    "value_inv_2_desc": "ຄວາມໃກ້ຊິດກັບເຊັນທຣັນເຟສຕິວໍຮັບປະກັນຄວາມຕ້ອງການທີ່ສູງຢ່າງຕໍ່ເນື່ອງທັງຈາກຄົນທ້ອງຖິ່ນແລະຊາວຕ່າງຊາດ.",
    "value_inv_3_str": "ການເພີ່ມມູນຄ່າທຶນ:",
    "value_inv_3_desc": "ຕັ້ງຢູ່ໃນເຂດທີ່ຢູ່ອາໄສລະດັບພຣີມຽມທີ່ພັດທະນາໄວທີ່ສຸດຂອງຊຽງໃໝ່.",
    "feat_pool_title": "ສະລອຍນ້ຳແບບຣີສອດຂະໜາດໃຫຍ່",
    "feat_pool_desc": "ຜ່ອນຄາຍໃນສະລອຍນ້ຳສ່ວນລວມທີ່ກວ້າງຂວາງແປ໊ດລ່າຍ, ເຊິ່ງໄດ້ຮັບຄະແນນສູງຈາກຜູ້ຢູ່ອາໄສໃນດ້ານຄວາມສະອາດ ແລະ ຂະໜາດ.",
    "feat_gym_title": "ສູນອອກກຳລັງກາຍ",
    "feat_gym_desc": "ຟິດເນດທີ່ມີເຄື່ອງມືຄົບວົງຈອນທີ່ທັນສະໄໝເບິ່ງເຫັນສວນແບບຣີສອດທີ່ຂຽວສົດຊື່ນ, ເໝາະສຳລັບກິດຈະວັດເພື່ອສຸຂະພາບຂອງທ່ານ.",
    "feat_walk_title": "ທາງຍ່າງສ່ວນຕົວ",
    "feat_walk_desc": "ທາງຍ່າງສ່ວນຕົວທີ່ເຊື່ອມຕໍ່ຄອນໂດມີນຽມໂດຍກົງຫາ Central Festival ຊຽງໃໝ່.",
    "feat_peace_title": "ສະພາບແວດລ້ອມທີ່ງຽບສະຫງົບ",
    "feat_peace_desc": "ຕັ້ງຢູ່ໃນເຂດຟ້າຮ່າມທີ່ງຽບສະຫງົບ, ສະເຫນີການລົບຫນີທີ່ງຽບສະຫງົບໃນຂະນະທີ່ຂັບລົດພຽງແຕ່ 10 ນາທີໄປຫາເມືອງເກົ່າທີ່ມີຊີວິດຊີວາ.",
    "feat_park_title": "ພື້ນທີ່ຈອດລົດ",
    "feat_park_desc": "ມີບ່ອນຈອດລົດກວ້າງຂວາງສຳລັບຊາວເມືອງ ແລະ ແຂກຂອງພວກເຂົາ.",
    "feat_sec_title": "ລະບົບຮັກສາຄວາມປອດໄພ 24/7",
    "feat_sec_desc": "ຄວາມສະຫງົບໃນໃຈທີ່ສົມບູນດ້ວຍການຮັກສາຄວາມປອດໄພຕະຫຼອດເວລາແລະ CCTV.",
    "loc_condo_name": "dcondo Ping by Sansiri",
    "loc_condo_addr": "ຟ້າຮ່າມ, ເມືອງຊຽງໃໝ່, ຊຽງໃໝ່ 50000",
    "loc_condo_desc": "ຕັ້ງຢູ່ໃກ້ກັບ Central Festival ທີ່ໂດດເດັ່ນດ້ວຍທາງຍ່າງສ່ວນຕົວກັບຜູ້ຢູ່ອາໄສ, ສະໜອງການດຳລົງຊີວິດທີ່ງຽບສະຫງົບລຽບຕາມແມ່ນ້ຳປິງ.",
    "loc_card1_title": "ເຊັນທຣັນເຟສຕິວໍ ຊຽງໃໝ່",
    "loc_card1_desc": "ແຫຼ່ງຊ້ອບປິ້ງ, ຮ້ານອາຫານ, ແລະ ສະຖານບັນເທີງອັນດັບຕົ້ນໆ.",
    "loc_card1_dist": "200ມ (ທາງຍ່າງສ່ວນຕົວ)",
    "loc_card2_title": "ຖະໜົນນິມມານເໝິນ",
    "loc_card2_desc": "ຄາເຟ່ຍອດຮິດ, ຮ້ານບູຕິກ, ແລະ ຊີວິດກາງຄືນ.",
    "loc_card2_dist": "ຂັບລົດປະມານ 10 ນາທີ",
    "loc_card3_title": "ເມືອງເກົ່າຊຽງໃໝ່",
    "loc_card3_desc": "ວັດປະຫວັດສາດ, ຕະຫຼາດນັດວັນອາທິດ, ສູນວັດທະນະທຳ.",
    "loc_card3_dist": "ຂັບລົດປະມານ 10 ນາທີ",
    "loc_card4_title": "ສູນການຄ້າ ເມຢ່າ ໄລຟ໌ສະຕາຍ",
    "loc_card4_desc": "ຫ້າງສັບພະສິນຄ້າໄລຟ໌ສະຕາຍລະດັບພຣີມຽມພ້ອມໂຮງໜັງ, ຮ້ານອາຫານ, ແລະ ບາເທິງດາດຟ້າ.",
    "loc_card4_dist": "ຂັບລົດປະມານ 10 ນາທີ",
    "loc_card5_title": "ມະຫາວິທະຍາໄລຊຽງໃໝ່ (ມຊ)",
    "loc_card5_desc": "ມະຫາວິທະຍາໄລຊັ້ນນຳໃນພາກເໜືອຂອງປະເທດໄທທີ່ມີວິທະຍາເຂດສີຂຽວສົດຊື່ນ.",
    "loc_card5_dist": "ຂັບລົດປະມານ 12 ນາທີ",
    "loc_card6_title": "ປະຕູທ່າແພ",
    "loc_card6_desc": "ສະຖານທີ່ສຳຄັນທາງປະຫວັດສາດທີ່ເປັນສັນຍາລັກ ແລະ ທາງເຂົ້າສູ່ເມືອງເກົ່າ.",
    "loc_card6_dist": "ຂັບລົດປະມານ 10 ນາທີ",
    "loc_card7_title": "ໂຮງໝໍກຸງເທບ ຊຽງໃໝ່",
    "loc_card7_desc": "ບໍລິການເບິ່ງແຍງສຸຂະພາບແລະການແພດລະດັບພຣີມຽມ.",
    "loc_card7_dist": "1.5 ກິໂລແມັດ",
    "loc_card8_title": "ສະໜາມບິນນານາຊາດຊຽງໃໝ່",
    "loc_card8_desc": "ຖ້ຽວບິນພາຍໃນ ແລະ ຕ່າງປະເທດ.",
    "loc_card8_dist": "7.5 ກິໂລແມັດ",
    "contact_col_loc_desc": "dcondo Ping ໂດຍ Sansiri<br>ຟ້າຮ່າມ, ເມືອງຊຽງໃໝ່ 50000"
  },
  "ja": {
    "featured_title": "おすすめ物件：dcondo Ping",
    "featured_subtitle": "モダンな暮らし。チェンマイの発展とピン川の魅力を融合。",
    "about_title": "ピン川からインスパイアされて",
    "about_desc": "2018年に有名デベロッパーSansiriによって開発されたdcondo Pingは、8階建の4棟、計687戸で構成されています。静かなファーハム地区に位置し、自然に囲まれた平穏な都市生活を提供します。広大な共用エリアはピン川の魅力から着想を得ています。数分でセントラルフェスティバル・チェンマイに直結する専用のプライベート・ウォークウェイがあり、国際空港までわずか7kmという比類ない利便性をお楽しみいただけます。",
    "stat_room_desc": "スタジオ(30)、1ベッド(37)、2ベッド(60) sq.m.",
    "stat_scale_desc": "4棟、8階建、687戸",
    "stat_loc_desc": "セントラルフェスティバルへの専用通路",
    "price_amount": "230万バーツ",
    "value_main_title": "dcondo Pingが選ばれる理由",
    "value_main_subtitle": "理想の我が家をお探しの方にも、高利回りの資産をお探しの方にも、ご満足いただけます。",
    "value_live_1_str": "静かなリトリート：",
    "value_live_1_desc": "都会の喧騒から離れた、穏やかなリゾートスタイルの環境です。",
    "value_live_2_str": "日常の利便性：",
    "value_live_2_desc": "ショッピングや食事に便利なセントラルフェスティバルへの直接専用通路があります。",
    "value_live_3_str": "プレミアムな設備：",
    "value_live_3_desc": "広大なプール、モダンなジム、美しく整備された庭園をお楽しみください。",
    "value_inv_1_str": "高利回り：",
    "value_inv_1_desc": "<strong>月額15,000バーツ</strong>（目標粗利回り7.5%）からという実績ある賃貸レートで、高い利回りを生み出します。",
    "value_inv_2_str": "圧倒的な需要：",
    "value_inv_2_desc": "セントラルフェスティバルに近いことで、地元の方と外国人の両方から常に高い需要があります。",
    "value_inv_3_str": "資産価値の向上：",
    "value_inv_3_desc": "チェンマイで最も急速に発展している高級住宅地の中心に位置しています。",
    "feat_pool_title": "巨大なリゾートプール",
    "feat_pool_desc": "清潔さと広さで居住者から高く評価されている、広々とした輝く共用プールでリラックスしてください。",
    "feat_gym_title": "フィットネスセンター",
    "feat_gym_desc": "緑豊かなリゾートスタイルの庭園を見渡す最新設備のジム。毎日の健康管理に最適です。",
    "feat_walk_title": "プライベートウォークウェイ",
    "feat_walk_desc": "コンドミニアムからセントラルフェスティバル・チェンマイに直結する専用の遊歩道です。",
    "feat_peace_title": "静かな環境",
    "feat_peace_desc": "活気ある旧市街まで車でわずか10分でありながら、静かなファーハム地区に位置し、穏やかな隠れ家を提供します。",
    "feat_park_title": "駐車場",
    "feat_park_desc": "居住者とゲストのための十分な駐車スペースをご用意しています。",
    "feat_sec_title": "24時間セキュリティ",
    "feat_sec_desc": "24時間体制のセキュリティとCCTVで完全に安心していただけます。",
    "loc_condo_name": "dcondo Ping by Sansiri",
    "loc_condo_addr": "チェンマイ県ムアンチェンマイ郡ファーハム 50000",
    "loc_condo_desc": "居住者専用の通路がありセントラルフェスティバルに非常に近く、ピン川沿いの静かな生活を提供します。",
    "loc_card1_title": "セントラルフェスティバル・チェンマイ",
    "loc_card1_desc": "一流のショッピング、食事、エンターテイメント。",
    "loc_card1_dist": "200m（専用通路）",
    "loc_card2_title": "ニマンヘミン通り",
    "loc_card2_desc": "トレンディなカフェ、ブティック、ナイトライフ。",
    "loc_card2_dist": "車で約10分",
    "loc_card3_title": "チェンマイ旧市街",
    "loc_card3_desc": "歴史ある寺院、サンデーナイトマーケット、文化の中心。",
    "loc_card3_dist": "車で約10分",
    "loc_card4_title": "MAYA ライフスタイル ショッピング センター",
    "loc_card4_desc": "映画館、レストラン、ルーフトップバーを備えた高級モール。",
    "loc_card4_dist": "車で約10分",
    "loc_card5_title": "チェンマイ大学（CMU）",
    "loc_card5_desc": "緑豊かなキャンパスを持つタイ北部のトップ大学。",
    "loc_card5_dist": "車で約12分",
    "loc_card6_title": "ターペー門",
    "loc_card6_desc": "象徴的な歴史的ランドマーク、旧市街への入り口。",
    "loc_card6_dist": "車で約10分",
    "loc_card7_title": "バンコク病院チェンマイ",
    "loc_card7_desc": "プレミアムなヘルスケアおよび医療サービス。",
    "loc_card7_dist": "1.5 km",
    "loc_card8_title": "チェンマイ国際空港",
    "loc_card8_desc": "国内線および国際線。",
    "loc_card8_dist": "7.5 km",
    "contact_col_loc_desc": "dcondo Ping by Sansiri<br>チェンマイ県ムアンチェンマイ郡ファーハム 50000"
  },
  "ko": {
    "featured_title": "추천 매물: dcondo Ping",
    "featured_subtitle": "현대적인 라이프스타일. 치앙마이의 성장과 핑 강의 매력이 어우러집니다.",
    "about_title": "핑 강에서 영감을 받다",
    "about_desc": "유명 개발사 산시리(Sansiri)가 2018년에 개발한 dcondo Ping은 4개의 8층 건물에 걸쳐 687세대로 구성되어 있습니다. 평화로운 파함(Fa Ham) 지역에 위치하여 자연으로 둘러싸인 조용한 도시 생활을 제공합니다. 핑 강의 매력에서 영감을 받은 넓은 공용 공간을 갖추고 있습니다. 전용 통로를 통해 센트럴 페스티벌 치앙마이(Central Festival Chiang Mai)까지 단 몇 분 만에 도달할 수 있으며, 국제공항은 7km 거리에 불과한 탁월한 편리함을 누려보세요.",
    "stat_room_desc": "스튜디오(30), 1베드(37), 2베드(60) sq.m.",
    "stat_scale_desc": "4개동, 8층, 687세대",
    "stat_loc_desc": "센트럴 페스티벌 전용 통로 연결",
    "price_amount": "฿230만 바트",
    "value_main_title": "왜 dcondo Ping인가요?",
    "value_main_subtitle": "완벽한 보금자리를 원하시거나 고수익 자산을 원하시거나, 이 숙소는 그에 부합합니다.",
    "value_live_1_str": "평화로운 휴식:",
    "value_live_1_desc": "이 조용하고 리조트 같은 환경에서 도시의 소음을 피해 휴식을 취하세요.",
    "value_live_2_str": "일상의 편리함:",
    "value_live_2_desc": "모든 쇼핑 및 다이닝 요구를 충족할 수 있는 센트럴 페스티벌로 연결된 프라이빗 통로입니다.",
    "value_live_3_str": "프리미엄 시설:",
    "value_live_3_desc": "거대한 수영장, 현대적인 체육관, 아름답게 조경된 정원을 즐겨보세요.",
    "value_inv_1_str": "높은 임대 수익률:",
    "value_inv_1_desc": "<strong>월 ฿15,000</strong>부터 시작하는 검증된 임대료로 견고한 수익을 창출합니다. (목표 총수익률 7.5%)",
    "value_inv_2_str": "비교불가한 수요:",
    "value_inv_2_desc": "센트럴 페스티벌이 가까워 현지인 및 외국인 모두에게서 지속적으로 높은 수요가 발생합니다.",
    "value_inv_3_str": "자본 가치 상승:",
    "value_inv_3_desc": "치앙마이에서 가장 빠르게 발전하는 프리미엄 주거 중심지에 위치합니다.",
    "feat_pool_title": "거대한 리조트 풀",
    "feat_pool_desc": "거주자들로부터 청결함과 크기로 높은 평가를 받는 반짝이는 대형 공용 수영장에서 휴식을 취하세요.",
    "feat_gym_title": "피트니스 센터",
    "feat_gym_desc": "아름다운 리조트풍 정원을 내려다보는 현대식 헬스장이 건강한 일상을 위해 완벽하게 갖춰져 있습니다.",
    "feat_walk_title": "프라이빗 통로",
    "feat_walk_desc": "콘도미니엄과 센트럴 페스티벌 치앙마이를 직접 연결하는 전용 산책로.",
    "feat_peace_title": "평화로운 환경",
    "feat_peace_desc": "조용한 파함(Fa Ham) 지역에 자리잡고 있어 활기찬 구시가지(Old City)까지 차로 단 10분 거리에 있으면서도 평화로운 휴식을 제공합니다.",
    "feat_park_title": "주차 공간",
    "feat_park_desc": "입주자 및 방문객을 위한 충분한 주차 공간이 마련되어 있습니다.",
    "feat_sec_title": "연중무휴 24시간 보안 시스템",
    "feat_sec_desc": "24시간 보안 및 CCTV로 완벽한 안심을 제공합니다.",
    "loc_condo_name": "dcondo Ping by Sansiri",
    "loc_condo_addr": "치앙마이 주 므앙 치앙마이 군 파함 50000",
    "loc_condo_desc": "입주민 전용 통로로 센트럴 페스티벌에 매우 인접하며, 핑 강변의 평온한 생활을 제공합니다.",
    "loc_card1_title": "센트럴 페스티벌 치앙마이",
    "loc_card1_desc": "쇼핑, 다이닝, 엔터테인먼트의 중심지.",
    "loc_card1_dist": "200m (전용 통로)",
    "loc_card2_title": "님만해민 로드",
    "loc_card2_desc": "트렌디한 카페, 부티크, 그리고 나이트라이프.",
    "loc_card2_dist": "차로 약 10분",
    "loc_card3_title": "치앙마이 올드 시티",
    "loc_card3_desc": "역사적인 사원, 선데이 나이트 마켓, 문화의 중심.",
    "loc_card3_dist": "차로 약 10분",
    "loc_card4_title": "마야 라이프스타일 쇼핑 센터",
    "loc_card4_desc": "영화관, 레스토랑, 루프탑 바를 갖춘 프리미엄 라이프스타일 몰.",
    "loc_card4_dist": "차로 약 10분",
    "loc_card5_title": "치앙마이 대학교(CMU)",
    "loc_card5_desc": "푸르른 캠퍼스를 자랑하는 태국 북부 최고의 명문대.",
    "loc_card5_dist": "차로 약 12분",
    "loc_card6_title": "타페 게이트",
    "loc_card6_desc": "치앙마이를 대표하는 역사적 랜드마크와 구시가지의 관문.",
    "loc_card6_dist": "차로 약 10분",
    "loc_card7_title": "방콕 병원 치앙마이",
    "loc_card7_desc": "프리미엄 헬스케어 및 의료 서비스.",
    "loc_card7_dist": "1.5 km",
    "loc_card8_title": "치앙마이 국제 공항",
    "loc_card8_desc": "국내선 및 국제선 항공편 운항.",
    "loc_card8_dist": "7.5 km",
    "contact_col_loc_desc": "dcondo Ping by Sansiri<br>치앙마이 파함 50000"
  }
};

const propertyBasePath = "asset/properties/condo/dcondo-ping/";

const propertyGallery = [
    { src: "building/LINE_ALBUM_คอนโด_260224_1.jpg", category: "building" },
    { src: "bedroom/LINE_ALBUM_คอนโด_260224_2.jpg", category: "bedroom" },
    { src: "bedroom/LINE_ALBUM_คอนโด_260224_3.jpg", category: "bedroom" },
    { src: "livingroom/LINE_ALBUM_คอนโด_260224_4.jpg", category: "livingroom" },
    { src: "livingroom/LINE_ALBUM_คอนโด_260224_5.jpg", category: "livingroom" },
    { src: "livingroom/LINE_ALBUM_คอนโด_260224_6.jpg", category: "livingroom" },
    { src: "livingroom/LINE_ALBUM_คอนโด_260224_7.jpg", category: "livingroom" },
    { src: "bedroom/LINE_ALBUM_คอนโด_260224_8.jpg", category: "bedroom" },
    { src: "livingroom/LINE_ALBUM_คอนโด_260224_9.jpg", category: "livingroom" },
    { src: "toilet/LINE_ALBUM_คอนโด_260224_10.jpg", category: "toilet" },
    { src: "kitchen/LINE_ALBUM_คอนโด_260224_11.jpg", category: "kitchen" },
    { src: "bedroom/LINE_ALBUM_คอนโด_260224_12.jpg", category: "bedroom" },
    { src: "livingroom/LINE_ALBUM_คอนโด_260224_13.jpg", category: "livingroom" },
    { src: "livingroom/LINE_ALBUM_คอนโด_260224_14.jpg", category: "livingroom" },
    { src: "livingroom/LINE_ALBUM_คอนโด_260224_15.jpg", category: "livingroom" },
    { src: "kitchen/LINE_ALBUM_คอนโด_260224_16.jpg", category: "kitchen" },
    { src: "laundry/LINE_ALBUM_คอนโด_260224_17.jpg", category: "laundry" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_18.jpg", category: "facilities" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_19.jpg", category: "facilities" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_20.jpg", category: "facilities" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_21.jpg", category: "facilities" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_22.jpg", category: "facilities" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_23.jpg", category: "facilities" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_24.jpg", category: "facilities" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_25.jpg", category: "facilities" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_26.jpg", category: "facilities" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_27.jpg", category: "facilities" },
    { src: "facilities/LINE_ALBUM_คอนโด_260224_28.jpg", category: "facilities" },
    { src: "LINE_ALBUM_คอนโด_260224_30.jpg", category: "livingroom" }
];
